### ISSUE TITLE
"Inavlid Swift Support" error when attempting to upload to the app store

### ISSUE THREAD

**Issue by icecrystal23** [openbakery/gradle-xcodePlugin#117]
We got an error attempting to upload our app earlier this month due to a missing SwiftSupport folder.  Apparently this is a bug in the Xcode command line tools.  To work around the issue, we had to manually repackage the app with some Swift libraries included.

According to this Apple dev forum thread, "Using PackageApplication is not supported":
https://devforums.apple.com/message/1042117#1042117

I will probably update my fork of the plugin to optionally apply this additional step to the package task:
https://github.com/bq/iOS-Scripting-PackageApplication-Swift-Support

**Comment by renep** [comment]
With the latest 0.10.0-beta8 it is possible to create correct ipa that can be uploaded to apple.

I have tested this with an example swift app and used the `package` task to create the ipa and uploaded it with the `appleUpload` task to itunesconnect.
