### ISSUE TITLE
Archiving problem on plugin version 0.10.0-beta8

### ISSUE THREAD

**Issue by tanob** [openbakery/gradle-xcodePlugin#131]
https://github.com/openbakery/gradle-xcodePlugin/blob/develop/plugin/src/main/groovy/org/openbakery/configuration/XcodeConfigTask.groovy#L89

_Xcode plugin version 0.10.0-beta8_

It seems that `objects.TARGET.productName` doesn't always has what you'd expect for your "Product Name". I actually couldn't find a way in Xcode to change that value after the target was created.

This is how I see Xcode dealing with "Product name":

* when you add a new target, it sets "Product name" to be "${TARGET_NAME}" (and it seems TARGET_NAME comes from the "name" attribute of a PBXNativeTarget)
* if you set "Product name" to be something different, then Xcode will put that in `objects.TARGET.buildSettings.PRODUCT_NAME`

Maintaining this kind of logic in the plugin sounds too complicated, wouldn't be easier to actually just use `xcodebuild -exportArchive`?

Here's why I started digging into this:

```
20:05:34.618 [DEBUG] [org.gradle.api.internal.project.ant.AntLoggingAdapter] Execute:Java13CommandLauncher: Executing '/bin/cp' with arguments:
'-rp'
'/Users/adriano/Projects/foo/build/sym-distribution/TargetOne/Release-iphoneos/SchemeName.app'
'/Users/adriano/Projects/foo/build/archive/SchemeName.xcarchive/Products/Applications'

The ' characters around the executable and arguments are
not part of the command.
20:05:34.627 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:exec] cp: /Users/adriano/Projects/foo/build/sym-distribution/TargetOne/Release-iphoneos/SchemeName.app: No such file or directory
```

"TargetOne" is the target I'm archiving but my project.pbxproj has `objects.TargetOne.productName` set to "SchemeName" for all the targets I have. The only way I found to change `productName` is to manually edit the project.pbxproj... that's why I think we can't trust that value to be the "Product name" that we expect.

**Comment by renep** [comment]
What about?:

1. if the value of the productName is ${TARGET_NAME} then the target name should be taken from the PBXNativeTarget setting
2. if you set xcodebuild.productName in your build.gradle file, than this value overwritten by the config task.

**Comment by renep** [comment]
Option 2 is now implemented in beta9

**Comment by tanob** [comment]
Thanks for the fast turnaround @renep !
