### ISSUE TITLE
/null/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos

### ISSUE THREAD

**Issue by savage7** [openbakery/gradle-xcodePlugin#132]
Version: 0.10.0
Xcode Version: 6.1.1 (6A2008a)
This is probably related to #118. When I build a Swift based App I get a FileNotFound Exception.
This also happens if I check out the example and add Swift Support. It seams the XCode.app isn't resolved correctly.

java.io.FileNotFoundException: /gradle-xcodePlugin-master/example/iOS/Example/null/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphoneos

**Comment by renep** [comment]
I have added a swift example app, and I can build with it 'gradle appstore' and upload it using 'gradle appstoreUpload'.
You need to set the signing settings, mobile provisioning profile and bundle identifier by modifying the build.gradle or you create a gradle.properties.

**Comment by savage7** [comment]
I did the same, still there's "null" for the Xcode path. Without swift support it builds.

**Comment by renep** [comment]
do you use the latest 0.10.1 build?

**Comment by savage7** [comment]
:) ok it was 0.10.0. With 0.10.1 it works!
