### ISSUE TITLE
how can i package a .ipa file?

### ISSUE THREAD

**Issue by philZH** [openbakery/gradle-xcodePlugin#136]
hi,  i need a .ipa file to test. how can i do?
thanks.

**Comment by renep** [comment]
You can do this with the 'package' task but you have to set the codesign settings.

see https://github.com/openbakery/gradle-xcodePlugin/tree/master/example/iOS/Example

In the build.gradle file at the top are instructions what values needs to be set.
You get the p12 file by exporting the certificate from your keychain.

In the example I have added a new task 'release' that depends on the package task and uses the codesign settings you have specified. So run 'gradle release'

**Comment by philZh** [comment]
thanks, got it.
have a new question.
how can i user testflight task?
can you give me a example?

**Comment by philZh** [comment]
i use this on build.gradle
...
 tasks.testflight.mustRunAfter tasks.package
...
// ------------------------------------------------------------------------------------------
	if (taskGraph.hasTask(tasks.testflight)) {
		//println ("using api token: " + testflighApiToken)
		testflight{
			apiToken = 'myapitoken'
			teamToken = 'd06708af57633a629b40e541d2ac01a....'
		}
	}
...


sudo gradle testflight
:testflight FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testflight'.
> Could not find method prepare() for arguments [] on task ':testflight'.

**Comment by renep** [comment]
For the testflight task you do not need the `taskGraph.hasTask`

You only need this if the configuration should be altered during the task execution. This is when the name of the task (e.g. 'release') determines with configuration should be used. 

see http://openbakery.org/gradle.php where I have simple testflight example. (For the old testflight, not the new apple testflight)

**Comment by philZh** [comment]
^_^ got it.
thank you so much.

**Comment by HeEAaD** [comment]
@philZh Have you a solution for your problem. I am experience the same problem/exception with testflight since 0.10.0.

**Comment by HeEAaD** [comment]
Ok, i found the problem: TestFlightUploadTask want to call `prepare()` but there is not such method. https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/testflight/TestFlightUploadTask.groovy#L56
Will open an issue for it.

**Comment by renep** [comment]
see Issue #141

**Comment by saravnandm** [comment]
Hi,
is there any support for hockey app? I mean to build, convert to IPA and upload to hockey app. If so any samples ?

**Comment by renep** [comment]
Yes here is hockeyapp support but it is quite old and I haven't it tested for quite some time: 
http://openbakery.org/gxp/parameters/hockeyapp.html

Also Microsoft discontinues hockeyapp, and I don't know if the App-Center is compatible with HockeyApp.

I for myself use Apples TestFlight. You can upload the IPA using the `appstoreUpload`: http://openbakery.org/gxp/parameters/appstore.html

**Comment by saravnandm** [comment]
After executing 'gradle hockapp' getting this error. Also, can we publish IPA and .framework file via gradle?

Execution failed for task ':hockeyapp'.
> dSYM not found: /Volumes/Secondary/workspace/ios/Test App/build/archive/TestApp.xcarchive/dSYMs/Test.app.dSYM
