### ISSUE TITLE
InfoPlist task does not consider overrides in taskGraph

### ISSUE THREAD

**Issue by txuslee** [openbakery/gradle-xcodePlugin#137]
Hi,
I'm trying to override a value in info.plist for specific execution targets and I can't get it to work. I have this default configuration:
    
    xcodebuild {
      workspace = "${projectDir}/Project.xcodeproj/project.xcworkspace"
      target = 'Project'
      //scheme = 'Project'
      configuration = 'Debug'
      sdk = 'iphoneos'

      //infoPlist = "${projectDir}/Project/Project-Info.plist"
      infoplist {
        shortVersionString = "1.0"
        version = "1.0.1"
        commands = [
          'Set :isProduction bool NO'
        ]
      }
    ...

The value I want to override is 'isProduction', but when I run any of the following target tasks the value still remains the same:

    if (taskGraph.hasTask(release) || taskGraph.hasTask(releaseOTA)) {
      xcodebuild {
        configuration = 'Release'
        infoplist {
          commands = [
            'Set :isProduction bool YES'
          ]
        }      
      }
    }

Thanks in advance for this great plugin :)

**Comment by renep** [comment]
the infoplist settings are top level settings, not within the xcodebuild settings:

```
if (taskGraph.hasTask(release) || taskGraph.hasTask(releaseOTA)) {
  xcodebuild {
    configuration = 'Release'
  }

  infoplist {
    commands = [
      'Set :isProduction bool YES'
    ]
  }      
}
```

**Comment by txuslee** [comment]
Thank you, that solved the problem.
