### ISSUE TITLE
0.10.1 testflight task leads to an exception

### ISSUE THREAD

**Issue by HeEAaD** [openbakery/gradle-xcodePlugin#141]
Affected Versions: 0.10.0 - 0.10.1

The `testflight` task will lead to an exception:
```
:testflight FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':testflight'.
> Could not find method prepare() for arguments [] on task ':testflight'.
```

Issue:
TestFlightUploadTask want to call prepare() but there is not such method. https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/testflight/TestFlightUploadTask.groovy#L56

**Comment by renep** [comment]
Can you please try version '0.10.2-beta1' that should fix this issue!

**Comment by renep** [comment]
I delete the testflight task now, because testflight closes on the 26th Feb 2015.
see http://help.testflightapp.com/customer/portal/articles/1768754
