### ISSUE TITLE
0.10.1 deploygate task an exception

### ISSUE THREAD

**Issue by katsutomu** [openbakery/gradle-xcodePlugin#143]
The deploygate task will lead to an exception:

    What went wrong:
    * Execution failed for task ':deploygate'.
    
    > Cannot get property 'absolutePath' on null object
    * Try:
    Run with --stacktrace option to get the stack trace. `

https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/deploygate/DeployGateUploadTask.groovy

not call prepare?

**Comment by renep** [comment]
should now work with 0.10.2-beta2

(see 822af6433debd5882d5a586cb736379ce40a90c2)

**Comment by katsutomu** [comment]
Thanks a lot !!!
