### ISSUE TITLE
:archive fails when project's ProductName is different than CFBundleName

### ISSUE THREAD

**Issue by txuslee** [openbakery/gradle-xcodePlugin#145]
Copy task previous to :archive fails to copy from build/sym/${CFBundleName}.app to build/archive folder if a different ProductName is chosen in project file.

**Comment by accedo-anz** [comment]
You can get a little further but adding the Product Name that you want e.g.
      bundleName='Neon'
inside xcodebuild section

however it then fails later in the package step i.e. if I have:

xcodebuild {                   
      scheme = 'Neon Prelive'     
      configuration = 'Prelive'
      sdk = 'iphoneos'
      bundleName='Neon'
     bundleNameSuffix = "-prelive-${BuildHelper.versionName}_${BuildHelper.versionCode}"      
  }

where BuildHelper.versionName=1.3.0 and BuildHelper.versionCode=3

I get the following error:
19:10:46.453 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':package'.
19:10:46.454 [ERROR] [org.gradle.BuildExceptionReporter] > app directory not found: /Users/me/git/project-ios/build/archive/Neon-prelive-1.3.0_3.xcarchive/Products/Applications/Neon-prelive-1.3.0_3.app

What is actually in the directory is:
build\archive\Neon-prelive-1.3.0_3.xcarchive\Products\Applications\Neon.app

**Comment by renep** [comment]
Until now the app name must be the same as the name of the xcarchive.

I think a solution would be that the first "*.app" directory that is found in `*.xcarchive/Products/Applications` is taken.
