### ISSUE TITLE
Multiple targets Xcode

### ISSUE THREAD

**Issue by AkhileshwarBV** [openbakery/gradle-xcodePlugin#157]
Hi renep,

I am using the gradle to build Xcode app

I have multiple targets in my app
1.Int
2.Debug
3.Prod

how can I build all targets at a time, I want to archive all the targets at a time with single script file

**Comment by renep** [comment]
No, not now see Issue #44

**Comment by AkhileshwarBV** [comment]
Hi renep
Thank you for the replay

I am getting an error says

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':build'.

No 'scheme' or 'target' specified, so do not know what to build
Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.707 secs
pbxddxl:Test deltatechnology$

Here I am seining my build script

buildscript {
repositories {
maven {
url('http://openbakery.org/repository/')
}
mavenCentral()
}
dependencies {
classpath group: 'org.openbakery', name: 'xcodePlugin', version: '0.9.+'
}
}
apply plugin: 'xcode'

xcodebuild {
configuration='Release'
sdk = 'iphoneos'
//target = 'Test'
additionalParameters = ["Test"]
signing {
identity = 'iPhone Distribution: Republic Services Inc. (YKXBJ5R297)'
certificateURI = 'file://localhost/Users/deltatechnology/Desktop/Cer/EmployeeDirectory/PrivateKey.p12'
certificatePassword = 'Password'
mobileProvisionURI = 'file://localhost/Users/deltatechnology/Desktop/Cer/EmployeeDirectory/Employee_Directory_Adhoc-3.mobileprovision'
}

}
