### ISSUE TITLE
When multiple test targets are in a scheme, test task junit output is partial

### ISSUE THREAD

**Issue by jaleksynas** [openbakery/gradle-xcodePlugin#158]
I have a single scheme with 2 test targets.  One for unit tests and one for KIF tests (if it matters). When running in Jenkins and gathering the junit xml file, I noticed that the second set of test results is missing from the XML.  The tests do get executed and are present in the xcodebuild-output.txt.  However they are not present in the xml.

**Comment by renep** [comment]
I have no idea how the output of the KIF tests looks like, but I think that it differs from unit test output. Therefor the result could not be parsed. But that is just guessing ;-)

I have no project using KIF test. You can help me by providing an example project with a setup where I can reproduce this issue e.g. by modifying the Example project in 'examples/iOS/Example'

**Comment by jaleksynas** [comment]
No longer able to reproduce.  Our codebase had a fleet of test adjustments and the problem has disappeared.  Will re-open with more details if it recurs.
