### ISSUE TITLE
Jankin gradle issue

### ISSUE THREAD

**Issue by AkhileshwarBV** [openbakery/gradle-xcodePlugin#159]
Hi renep

Unable to build Xcode with jenkins

I am making xcodebuild with gradle script from jenkins server
when I try to make a build from my terminal ebrything is working fine, but when I try to make a build from jerkin server I got following error.

please see the jnkins gradle out put
please help me to tiger out 

:xcodebuildConfig (Thread[main,5,main]) completed. Took 0.208 secs.
:infoplistModify (Thread[main,5,main]) started.
:infoplistModify
Executing task ':infoplistModify' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Updating /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/EmpDirDemo/Info.plist
:infoplistModify (Thread[main,5,main]) completed. Took 0.005 secs.
:keychainCreate (Thread[main,5,main]) started.
:keychainCreate
Executing task ':keychainCreate' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
[ant:get] Getting: file://localhost/Users/deltatechnology/Desktop/certificates/EmployeeDirectory/PrivateKey.p12
[ant:get] To: /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/codesign/PrivateKey.p12
[ant:get] .
import "/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/codesign/PrivateKey.p12" "-k" "/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/codesign/gradle-1426772317429.keychain" "-P" "Delta#123" "-T" "/usr/bin/codesign"
1 identity imported.
    "/Library/Keychains/System.keychain"
:keychainCreate (Thread[main,5,main]) completed. Took 0.195 secs.
:provisioningInstall (Thread[main,5,main]) started.
:provisioningInstall
Executing task ':provisioningInstall' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
[ant:get] Getting: file://localhost/Users/deltatechnology/Desktop/certificates/EmployeeDirectory/Employee_Directory_Adhoc-3.mobileprovision
[ant:get] To: /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/provision/Employee_Directory_Adhoc-3.mobileprovision
[ant:get] .
:provisioningInstall (Thread[main,5,main]) completed. Took 0.03 secs.
:xcodebuild (Thread[main,5,main]) started.
:xcodebuild
Executing task ':xcodebuild' (up-to-date check took 0.001 secs) due to:
  Task has not declared any outputs.
Build settings from command line:
    CODE_SIGN_IDENTITY = iPhone Distribution: Republic Services Inc. (YKXBJ5R297)
    CODE_SIGN_RESOURCE_RULES_PATH = $(SDKROOT)/ResourceRules.plist
    DSTROOT = /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/dst
    OBJROOT = /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/obj
    OTHER_CODE_SIGN_FLAGS = --keychain=/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/codesign/gradle-1426772317429.keychain
    PROVISIONING_PROFILE = 32dc6244-716b-48f1-ad3f-13893b9338a9
    SDKROOT = iphoneos8.1
    SHARED_PRECOMPS_DIR = /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/shared
    SYMROOT = /Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/sym

=== BUILD TARGET Contacts OF PROJECT Contacts WITH CONFIGURATION Release ===

Check dependencies
Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and private key pairs) that match the provisioning profile specified in your build settings (“Employee Directory Adhoc”) were found.
CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'

** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
:xcodebuild FAILED
:xcodebuild (Thread[main,5,main]) completed. Took 0.574 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xcodebuild'.
> Command failed to run (exit code 65): 'xcodebuild -configuration Release -sdk iphoneos -target Contacts CODE_SIGN_IDENTITY=iPhone Distribution: Republic Services Inc. (YKXBJ5R297) CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist PROVISIONING_PROFILE=32dc6244-716b-48f1-ad3f-13893b9338a9 DSTROOT=/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/dst OBJROOT=/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/obj SYMROOT=/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/sym SHARED_PRECOMPS_DIR=/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/shared OTHER_CODE_SIGN_FLAGS=--keychain=/Users/Shared/Jenkins/Home/workspace/EmployeeDirectory_iOS/build/codesign/gradle-1426772317429.keychain'

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

BUILD FAILED

Total time: 3.503 secs
Build step 'Invoke Gradle script' changed build result to FAILURE
Build step 'Invoke Gradle script' marked build as failure
Finished: FAILURE

Thanks & regards,
Akhileshwar Babu

**Comment by renep** [comment]
Are you sure that your 
identity `iPhone Distribution: Republic Services Inc. (YKXBJ5R297)`
provisioning profile `Employee_Directory_Adhoc-3.mobileprovision` and key `PrivateKey.p12` matches.

The reason why it works on your local machine is, that you for example have installed the proper provisioning profile in ~/Library directory, or key in the login.keychain that does not exist on Jenkins.

**Comment by AkhileshwarBV** [comment]
Yes renew,
 am sure private key and identifier and provisioning profile are match.

I also tested jenkins workspaces code
i can able to make build for jerkin work space code in  my terminal


"Jenkin is installed in my mac only"

**Comment by renep** [comment]
The message says that they do not match:

> Check dependencies
> Code Sign error: No codesigning identities found: No codesigning identities (i.e. certificate and private key pairs) that match the provisioning profile specified in your build settings (“Employee Directory Adhoc”) were found.
> CodeSign error: code signing is required for product type 'Application' in SDK 'iOS 8.1'


> i can able to make build for jerkin work space code in my terminal
do you run this test as your user or a different? Your user maybe has additional certificates in the login.keychain, and if the proper certificate is not found in the keychain gradle creates that it is codesign searches the login keychain.

**Comment by AkhileshwarBV** [comment]
I run build from terminal with gradle script
and in my plist I did not set anything

Thanks you
