### ISSUE TITLE
Upload/Create Archive(IPA)  File To Shared/Specific Folder Through  Gradle Script.

### ISSUE THREAD

**Issue by AkhileshwarBV** [openbakery/gradle-xcodePlugin#160]
Hi Renep,

I can able to make IPA file. but my next task my client want add the current date to ipa file name (renaming IPA file) and also I have to upload /create the .ipa file to shared folder  through gradle script.

How can I upload the ipa file to specific /shared folder.

Please help me.

Thanks & Regards,
Akhileshwar Babu V

**Comment by renep** [comment]
see bundleNameSuffix parameter in https://github.com/openbakery/gradle-xcodePlugin/blob/master/Documentation/Parameters.md

For upload Jenkins as Plugins like FTP, SCP etc, or you can use HockeyApp, Hockeykit or Deploygate Services.

**Comment by AkhileshwarBV** [comment]
I want to upload IPA file directly from build script 
I want to upload to specific folder not for testing like Hockey app

**Comment by renep** [comment]
see http://lmgtfy.com/?q=gradle+ftp+upload

**Comment by AkhileshwarBV** [comment]
Thank you and I used some java based libraries in my script to achieve this
