### ISSUE TITLE
Cannot invoke method equalsIgnoreCase() on null object

### ISSUE THREAD

**Issue by IntelBob** [openbakery/gradle-xcodePlugin#164]
My project, generated via `cocoapods pod lib create`, has a number of default targets and I added a few of my own, one is an aggregate target, `xyz`, which is dependent on 2 other targets, `abc`, `def`. Executing a `maven-publish` task caused `xcodebuildConfig` to throw the error `Cannot invoke method equalsIgnoreCase() on null object`. I looked into the plugin code, `XcodeProjectFile.groovy` and sees it is breaking at line 73

    String type = config.getString("objects." + target + ".productType")
    if (type.equalsIgnoreCase("com.apple.product-type.app-extension")) {

I tracked that down to the aggregate target, `xyz`, in the `project.plist` file and it is missing `productType` and I can't seem to find a way to set this in Xcode but unsure it should be set in the first place since it is dependent on 2 other targets which have `productType`. Is this a bug and / or is there a workaround?

**Comment by andybest** [comment]
This fix doesn't seem to be in the most recent release (0.11.5)
