### ISSUE TITLE
0.10.3 cannot be downloaded

### ISSUE THREAD

**Issue by savage7** [openbakery/gradle-xcodePlugin#165]
I use these dependency in my gradle file:
classpath group: 'org.openbakery', name: 'xcodePlugin', version: '0.10.+'
As a workaround a set a fix 0.10.2 which works...

Since yesterday I get this error:
A problem occurred configuring root project 'ios'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.openbakery:xcodePlugin:0.10.+.
     Required by:
         :ios:unspecified
      > Could not GET 'http://openbakery.org/repository/org/openbakery/xcodePlugin/0.10.3/xcodePlugin-0.10.3.pom'. Received status code 300 from server: Multiple Choices

**Comment by renep** [comment]
Now you can because I have released the version now.
