### ISSUE TITLE
:provisioningInstall FAILED

### ISSUE THREAD

**Issue by prangya123** [openbakery/gradle-xcodePlugin#166]
while trying to provide signing in the build.gradle facing :provisioningInstall FAILED error.

if I do --exclude :provisioningInstall then it works fine. I need to build the same project for diff :provisioning profile.

can you please suggest what I am doing wrong?

 xcodebuild {
    target = 'Framework' // xcode target build.
    scheme = 'PluginTester'
    configuration = 'Release'
    sdk = 'iphoneos'

```
signing {
    identity = 'iPhone Distribution: **********.'
    mobileProvisionURI = '***************'
    certificateURI = "file://Users/USERHOME/Library/MobileDevice/Provisioning Profiles/Certificates.p12"
    certificatePassword = '********'
    keychainPassword= '**********'
            keychain= "Prangya Parmita"
```

)

**Comment by renep** [comment]
The `mobileProvisionURI` is a uri to your mobileprovising file.
You can download these from the iTunesConnect portal or find seem in `~/Library/MobileDevice/Provisioning Profiles`

The `certificateURI` is the certificate exported from you keychain as p12, and the `certificatePassword` is the password you picked.

You do not need the `keychain` and `keychainPassword` parameter.

Your config should look like this:
```
signing {
    identity = 'iPhone Distribution: **********.'
    mobileProvisionURI = 'file://Users/USERHOME/.../Certificates.mobileprovision'
    certificateURI = "file://Users/USERHOME/.../Certificates.p12"
    certificatePassword = '********'
}
```
