### ISSUE TITLE
Custom CocoaPods version

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#176]
Could it provide option to setup custom Cocoapods version to be installed/used?
Before using this plugin I solve this problem with **rvm**.

**Comment by renep** [comment]
Why is it necessary to choose the cocoapods version. Can you give me an example.

**Comment by BamX** [comment]
Some projects uses old version of Pods so new version could broke build.

**Comment by renep** [comment]
When you have installed the pods manually and there is a Pods directory the cocoapods install task is skipped by the gradle build. 
With this you can solve your problem. 
I have never run in into this issue, therefor I don't know if this problem occurs very often.

**Comment by BamX** [comment]
That's an idea. Thank you
