### ISSUE TITLE
AbstractDistributeTask.getArchiveDirectory() returns wrong directory when multiple targets are built

### ISSUE THREAD

**Issue by obxhdx** [openbakery/gradle-xcodePlugin#177]
If you have a project with multiple targets, and execute the `archive` task for each of them, sequently as follows:
`$ gradle archive -Ptarget=AppA`
`$ gradle archive -Ptarget=AppB`

The second execution will fail complaining that `AppB.ipa` was not found. And although AppB was specified, the code sign task happens against AppA.

This happens because [AbstractDistributeTask.getArchiveDirectory()](https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/AbstractDistributeTask.groovy#L142) gets index 0 of a list of all `*.xcarchive` folders, and as `AppA` was built first, `AppA.xcarchive` is returned.

Am I right to assume that `AbstractDistributeTask.getArchiveDirectory()` just needs to return `project.xcodebuild.archiveDirectory`?

If that's the case, perhaps this method can even be removed completely and the [extension method](https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/XcodeBuildPluginExtension.groovy#L420-L432) be used instead.

**Comment by renep** [comment]
I know of this issue and I want to address it in one of the next servers. 

As solution for now you can create your own task that depends on the archive task but afterwards moves the archive to a different location my using the gradle copy task. https://gradle.org/docs/current/userguide/working_with_files.html)
