### ISSUE TITLE
Support for multiple provisioning profiles (WatchKit)

### ISSUE THREAD

**Issue by kishyr** [openbakery/gradle-xcodePlugin#178]
In Xcode 6.2 and 6.3, when compiling for Apple Watch, the Watch App and Watch Extension require their own provisioning profiles. Currently, this plugin only allows specifying one provisioning profile. 

An [issue on xctool's repo](https://github.com/facebook/xctool/issues/495) recommends leaving out the provisioning profile and just using the `CODE_SIGN_IDENTITY` flag, but when you try to do this in this plugin's `signing` config, xcodebuild complains about a "`null`" provisioning profile being specified and not found.

**Comment by renep** [comment]
That is not correct, the 0.10.x and 0.11.0 supports multiple provisioning profiles ;-)

See also the example/iOS/Example/build.gradle

I have checked the Parameters documentation and found out that this is missing. I will add it.

Just specify an array:

```
mobileProvisionURI = [ signingMobileProvisionURI , signingMobileProvisionURIWidget ]
```

**Comment by kishyr** [comment]
Thanks @renep :-)
