### ISSUE TITLE
Build for iOS appends sets CODE_SIGNING_REQUIRED=NO

### ISSUE THREAD

**Issue by kishyr** [openbakery/gradle-xcodePlugin#180]
For some reason, whenever I compile for iOS, the following flags are added to `xcodebuild`: `CODE_SIGN_IDENTITY= CODE_SIGNING_REQUIRED=NO`. From reading the source, this should only happen if `signing` is nil or `identity` is not set (or if it's a Mac App). I have both `signing` and `identity` (inside `signing`) set. I have also set `sdk = "iphoneos"` inside `xcodebuild`. 

Any idea what else could cause this?

**Comment by renep** [comment]
With 0.11.1 the proper codesign identity is used again now.

I tried to also disable the code signing for iOS builds, but it is needed because of the entitlements.

**Comment by renep** [comment]
Codesign is disabled in version 0.12 now.
