### ISSUE TITLE
Cocoapods intsall could use wrong Ruby version

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#182]
Hi there!
There is a problem with pods. If your default ruby version is lower than 2.0.0 CocoaPods will not works. But there could be an acceptable version installed. Common way is something like that:
```
#rvm install 2.1.1 (if needed) 
rvm use ruby-2.1.1 
gem install cocoapods
```
I've tried to run that commands in my script before running "pod install", but Gradle runs commands in different bash sessions. How my problem could be solved without setting another ruby version by default for all?

**Comment by renep** [comment]
AFAIK ruby 2 is the default version since 10.9. Why should I support 10.8, if the current Xcode version does not run there?

**Comment by BamX** [comment]
I could install and set by default any version of ruby. It's environment problem for this plugin that I could not solve without configuring build agent just for build projects with this plugin. 
I think it could be solved just by running in cocoapods task something like that:
```
commandRunner.run("rvm", "use", "ruby-$rubyVersion", "&&", "gem", "install", "-N", "--user-install", "cocoapods");
```

**Comment by BamX** [comment]
But now I cant find out why command runner not using default ruby version, I've setted up by default with rvm. That is pretty strange.
