### ISSUE TITLE
Dependencies in Project

### ISSUE THREAD

**Issue by ghost** [openbakery/gradle-xcodePlugin#189]
Hi, 

I'm trying to include a framework created by me in a new project, using your plugin, but i'm kinda stuck. 
I got them to compile separately but i cannot get it to be added to my main-project.

Can you give me a little help? 
Do you support this?

**Comment by renep** [comment]
I have no project (until now) where I use shared projects, so I cannot say if this works or not. 
If you can create an example project with a framework and and app that uses, I can have a look.

What does work is cocoapods, so when you framework is included using cocoapods than this should work fine. If you project has a Podfile the plugin detects this and is should work out of the box.
