### ISSUE TITLE
Can not build iOS project applied with gradle-xcodePlugin on jenkins server

### ISSUE THREAD

**Issue by youjenli** [openbakery/gradle-xcodePlugin#194]
Hi everyone

I want to build a cordova-like source project with gradle on jenkins server to adopt continuous integration, but the build progress always hang up without any response on jenkins.  
This project includes shared web resources and several native projects which targets distinct mobile platform such as android , iOS.  
In the build script of iOS subproject I applied gradle-xcodePlugin to build iOS artifacts.<br />
These are the settings in iOS build script:  

	xcodebuild {
		target = 'SynnexAPPSynnexAPPIphone'
		scheme = 'SynnexAPPSynnexAPPIphone'
		sdk = 'iphoneos'
		configuration = 'Release'
	
		infoPlist = {
			bundleIdentifier = "{a-valid-bundle-id}"
			bundleDisplayName = 'Synnex'

			def buildType = extraProps.get('buildType')
			if('Release'.equalsIgnoreCase(buildType)){
				//shortVersionStringPrefix =
				shortVersionString = extraProps.get('versionName')
				shortVersionStringSuffix = buildType
			}
		
		}
		signing {
			certificateURI = 'file:///Users/stash/Documents/certificates/ios-dist-signing-private-key.p12'
			certificatePassword = "{my-password}"
			mobileProvisionURI = 'file:///Users/stash/Documents/provision/dist_provisioning_profile_for_synnexb2e201505.mobileprovision'		
		}
		ipaFileName = nameOfArtifact
	}

The whole project build succeed if I make gradle to run the build in command line, 
but fails if we place it on jenkins server and execute gradle build with jenkins gradle plugin, 
and I can't figure out what's wrong with it. 

The console output message of gradle xcode-plugin is  [in this file][2], which was generated on jenkins server with jenkins gradle plugin.  
The build process always hang up without any response after the last line in the previous link was printed out. And a successful build should have log message [like this one][1].  

Can anyone help me fix this problem? Any suggestion/comment is appreciated. 
Thank you!

[1]: https://drive.google.com/open?id=0B8d7WRHnGxbRTDFNTmtHTkxkTjg
[2]: https://drive.google.com/open?id=0B8d7WRHnGxbRZTB6d3VSWmFXNkE

**Comment by renep** [comment]
Hmm, I don't know what is executed in an cordova project, because I only do native stuff ;-)
Nevertheless, what I can see in the log is that the xcodebuild command is executed with the SynnexAPPSynnexAPPIphone scheme. 

Normally the source code should be compiled here. I have seen in the hello world cordova example that prior to the compile a shell script is executed. Maybe this script causes the freeze. Maybe. cordova needs to be installed on the jenkins build node.

Have you tried to execute the build manually on the build node?

**Comment by youjenli** [comment]
According to the console output message , it seems that the build process was frozen at the time it began to build Cordova library native project, which our iOS project depends on it.  
The cordova library project is located at the source folder of our iOS project, so I think they were configured in the same ios workspace?  
I am wondering if build commands of xcode fork new thread or new process to build dependency project...  
If that is true, I guest it could be the reason that makes jenkins gradle plugin to hang up.... Resources were often restricted on server.

**Comment by renep** [comment]
So the question is why the building of the Cordova library is freezing. Have you tried to execute the build on the jenkins  manually via ssh or remote desktop?

**Comment by youjenli** [comment]
After futher more investigation, I found out that source files of dependency project - cordova native library was missing. This problem can be fix easily.  

However, the gradle build process neither report a failure nor print out error message on jenkins when it attempts to build the broken cordova native library.  
It just freezed until we stop the build job manually....  That make us spent so much time to figure out what's going on.  

It would be great if anyone could adopt mechanism to prevent xcode build job hanging on jenkins in this case.

**Comment by renep** [comment]
Can you check if the xcodebuild process was running and the one that was freezing. If so, the only thing I can do is to add some checks that when xcodebuild does not produce any output for, lets say 5 minutes, that the process had freeze.

The other thing is, that this could be a xcodebuild issue. Have you tried to run it manually. In the debug log you find full xcodebuild command that is executed. Maybe this is an issue for an radar.

**Comment by youjenli** [comment]
Before we put this project on jenkins, we have already build this project successfully with gradle command line.
At that time the dependency project was generated and configured properly after checkout from vcs, 
but I didn't notice that it was not ready when we put this project on jenkins. 
That's why I think the missing dependency project is very likely to be the reason cause our build to fail.  

And... if you would like to check the xcode build process....  
I've found out that gradle build progress on jenkins replace the thread which works for previous step before building cordova native library with a new thread (Thread-22).  
![jenkins-visualvm](https://cloud.githubusercontent.com/assets/1283378/8929489/746d5144-3558-11e5-9c8d-fafea9de58a4.png)
Thread monitor view of visualvm  

![jenkins-console-output](https://cloud.githubusercontent.com/assets/1283378/8929511/adb13c7c-3558-11e5-89fa-e898d9f3ab21.png)
Console output from jenkins  

![thread-dump](https://cloud.githubusercontent.com/assets/1283378/8929572/143602c0-3559-11e5-8131-9cdd00b90e2f.png)
Thread dump message after gradle build process freezed.

It seems that the new thread was blocking for a file input stream which could be any source of the missing cordova library project.  Thus, I think if we define this case as an issue ... then it is likely to be either gradle or xcodePlugin doesn't fail that build when some files were missing.  

I hope this information can be helpful to you.

**Comment by renep** [comment]
It looks to me that the xcodebuild isself freezes, and if so than this is no issue of the gradle plugin itself. I will keep this in mind, in if this problem occurs more often, than it could make sense to add some checks. But for now I think it is not worth the effort.
