### ISSUE TITLE
updating version via shortVersionStringSuffix does not update all required files

### ISSUE THREAD

**Issue by tompson** [openbakery/gradle-xcodePlugin#207]
if I use `agvtool` like

`agvtool new-marketing-version 1.1.6`

it updates the plist files in my project like

```
Setting CFBundleShortVersionString of project Tour to:
    1.1.6.

Updating CFBundleShortVersionString in Info.plist(s)...

Updated CFBundleShortVersionString in "Tour.xcodeproj/../Tour/Tour-Info.plist" to 1.1.6
Updated CFBundleShortVersionString in "Tour.xcodeproj/../Tour/TourTest-Info.plist" to 1.1.6
Updated CFBundleShortVersionString in "Tour.xcodeproj/../tour WatchKit App/Info.plist" to 1.1.6
Updated CFBundleShortVersionString in "Tour.xcodeproj/../tour WatchKit Extension/Info.plist" to 1.1.6
```

but the plistinfo task only changes the `Tour-Info.plist` file

which causes the build to fail with

```
2015-09-08 16:19:46.565 xcodebuild[98426:3677849]  DVTAssertions: Warning in /SourceCache/IDEXcode3ProjectSupport/IDEXcode3ProjectSupport-7709/Xcode3Core/LegacyProjects/Frameworks/DevToolsCore/DevToolsCore/BuildSystem/Runtime/BuiltinTools/XCEmbeddedBinaryValidationUtilityCommandInvocation.m:448
Details:  Embedded binary validation utility error: Error Domain=IDEFoundationErrorDomain Code=1 "error: The value of CFBundleShortVersionString in your WatchKit app's Info.plist (1.1.6) does not match the value in your companion app's Info.plist (1.1.6_f907fd7). These values are required to match." UserInfo={NSLocalizedDescription=error: The value of CFBundleShortVersionString in your WatchKit app's Info.plist (1.1.6) does not match the value in your companion app's Info.plist (1.1.6_f907fd7). These values are required to match.}
```

**Comment by renep** [comment]
I do not want to use the agvtool, but I'll try to come up with a solution that works similar.

**Comment by tompson** [comment]
why not use agvtool?

**Comment by renep** [comment]
Because I have something in mind like:

`shortVersion = 1.0.1 (23)`

and a task bumpShortVersion that result in: `1.0.1 (24)`

**Comment by tompson** [comment]
ok, but that what 

```agvtool next-version -all```

does exactly that, or

```agvtool bump -all```

see https://developer.apple.com/library/ios/qa/qa1827/_index.html

**Comment by renep** [comment]
bump should only increase the last integer and the agvtool increase the first integer
e.g.
1.0.1 -> 1.0.2
2 -> 3
1.2 -> 1.3
1.my-fance-10-version -> 1.my-fance-11-version

In the first version I want to focus on bumping only the version.

Why?
What if the version and shortVersion are similar:
```
version = 1.0.1 (20)
shortVersion = 1.0.1
```

What should the values now be if I bump all versions?
```
version = 1.0.2 (20)
shortVersion = 1.0.2
```

or

```
version = 1.0.2 (1)
shortVersion = 1.0.2
```

or

```
version = 1.0.1 (21)
shortVersion = 1.0.2
```

**Comment by tompson** [comment]
I am following this blog post for versioning iOS apps: http://www.blog.montgomerie.net/easy-iphone-application-versioning-with-agvtool

In this case the ```version``` (```CFBundleVersion```) starts with 1 and the ```marketing-version``` (```CFBundleShortVersionString```) starts with 0.0.1

When I submit the next version to the app store I do

```agvtool bump -all```

which leads to ```CFBundleVersion``` being increased to 2 and 

```agvtool set-marketing-version 0.0.2``` which leads to ```CFBundleShortVersionString``` being set to 0.0.2

the version in the archive then shows ```0.0.2 (2)```
