### ISSUE TITLE
Switch to the new gradle rule base model

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#208]
With this the configuration syntax will change, but this will be a huge benefit for the plugin, because this makes it easy to build multiple targets and multiple configurations.

**Comment by jaredsburrows** [comment]
Maybe wait for Gradle 3.0: https://docs.gradle.org/current/userguide/software_model.html
```
Support for rule based configuration is currently incubating. Please be aware that the DSL, APIs and other configuration may change in later Gradle versions.
This chapter describes and documents what is essentially the foundation for Gradle 3.0 and the next generation of Gradle builds. It is being incrementally developed during the Gradle 2.x stream. Gradle's support for building native software and Play Framework applications already uses this configuration model. Gradle also includes some initial support for building Java libraries using this configuration model.
```

**Comment by renep** [comment]
The question is when the rule based model is final. This is a bigger issue to achive, and I don't want wait tool long, because it would be a great benefit.
Also I plan to do the implementiation in an own branch, and I think that the new model based system and the old system would coexists for some time.
