### ISSUE TITLE
Code signing fails because plist change doesn't seem respected

### ISSUE THREAD

**Issue by hannesoid** [openbakery/gradle-xcodePlugin#210]
After migrating from Xcode 6.4 to Xcode 7 and Xcode gradle plugin from 0.11.4 to 0.11.6, I have a problem with code signing. Somehow it seems the changes made to the infoplist are not respected by the code signing (or by the build process itself?).
Upon inspecting the info-plist itself, it has infact been changed as expected.

```
buildserver1:Continuous kadonaci$ gradle redactedAppStore
CONFIGURE APPSTORE
:cocoapods
:xcodebuildConfig
:infoplistModify
Updating /redacted/redacted-Info.plist
Set CFBundleIdentifier to com.redacted
Set CFBundleDisplayName to Redacted
Set Delete CFBundleURLTypes:0:CFBundleURLSchemes
Set Add CFBundleURLTypes:0:CFBundleURLSchemes array
Set Add CFBundleURLTypes:0:CFBundleURLSchemes:0 string redacted
Set Delete :UIFileSharingEnabled
:keychainClean
:keychainCreate
:provisioningClean
:provisioningInstall
:xcodebuild
   ERROR - CodeSign

Code Sign error: Provisioning profile does not match bundle identifier: 
The provisioning profile specified in your build settings (“REDACTED”) 
has an AppID of “com.redacted” which does not match your bundle 
identifier “com.redacted.develop”.
```

**Comment by hannesoid** [comment]
Okay, it seems Xcode7 wants to use the build setting PRODUCT_BUNDLE_IDENTIFIER and is not happy, when the bundle identifier in the info plist is hard coded and diverges from the PRODUCT_BUNDLE_IDENTIFIER setting.

So a solution is either:
- set the setting in Xcode for each build configuration as needed
or
- pass the setting via xcodebuild.additionalParameters instead of infoplist.bundleIdentifier

**Comment by renep** [comment]
The upcoming 0.12 version does not sign anymore during xcodebuild. The signing takes only place at the package task. Therefor this issue should not be happen anymore.
