### ISSUE TITLE
Removing keychain-access-groups?

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#220]
Hi @renep!

Why are you removing "keychain-access-groups"? It disallows keychain sharing, as I see. And this feature is very important in some of applications.

	// the keychain-access-groups were removed from the entitlements on the xcode export step
	// therefor I also remove this here. Maybe this is wrong, but I hope the future will clarify this.

https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/signing/ProvisioningProfileReader.groovy#L174

**Comment by renep** [comment]
As I have written in the comment, I try to do the same es Xcode do and Xcode has removed this from the entitlements.
The question is if this values must be in the entitlements when signing, or if the entry in the provisioning profile is sufficient.

I have no app to test this, there if anyone can clarify this it would be welcome ;-)

**Comment by BamX** [comment]
I've just look into entitlements of app with keychain share released to appstore and it have keychain-access-groups. Enterprise build have it too.
I've used codesign -d --entitlements - "MyApp.app"

**Comment by renep** [comment]
Have you looked in the xcent file when you create an archive. This is the entitlements that is used for signing. Here in my cause the keychain-access-groups is removed.

**Comment by BamX** [comment]
I've just archive another app with keychain sharing and it have keychain-access-groups in AppName.app.xcent.

**Comment by renep** [comment]
Do your app use keychain sharing?

I want to know if the current removal of the `keychain-access-groups` breaks something. I do not want to change something on suspicion.

**Comment by BamX** [comment]
Yep, this app is using keychain sharing(I've just enabled this feature to check)

**Comment by BamX** [comment]
So, what do you think about "removing removal"?

**Comment by renep** [comment]
Does your app NOT work as expected with the 0.12.2 version?
I mean does the keychain sharing not work? 
Can you confirm this?

**Comment by BamX** [comment]
I have app in TestFlight that build with 0.12.2 and there keychain sharing broken.
I think that it's critical to remove this line.

**Comment by BamX** [comment]
I've just made arhive+export and entitlements contains keychain-access-groups.

**Comment by renep** [comment]
I have create a 0.12.3-Test version and uploaded to to repository.openbakery.org for testing where I leave the value as it is.

Please test and let me know if it works now.

**Comment by BamX** [comment]
Thank you! Yes, now it works! Could you make a 0.12.3 release with this fix please?

**Comment by renep** [comment]
0.12.3 is out
