### ISSUE TITLE
Environment variables in Info.plist path

### ISSUE THREAD

**Issue by bamx23** [openbakery/gradle-xcodePlugin#221]
I think it is a problem:

```
Info Plist does not exist: /Users/bamx23/Documents/Projects/project-name/${SRCROOT}/some-dir/Info.plist
```

What do you think?

**Comment by renep** [comment]
Do you have in your build settings in the value for the Info.plist ${SRCROOT}?
I have only relative path here in my projects. Do you need SRCROOT here?
Can you give me more details when this happens.

**Comment by BamX** [comment]
Yes, it contains SRCROOT there. I can remove it, but don't you think that it's a problem?
