### ISSUE TITLE
Support for XCode 7 'enableCodeCoverage' in coverage task

### ISSUE THREAD

**Issue by mnology** [openbakery/gradle-xcodePlugin#225]
The coverage task as is utilizes gcov to facilitate coverage reporting. This doesn't work (coverage at 0%) with Swift projects developed with XCode 7. Using an additionalParameter of 'enableCodeCoverage' produces the XCode format where xml/html/txt would be preferable (for CI tasks / sonar analysis)

Desired functionality would be something along the lines of the slather gem: http://mgrebenets.github.io/mobile%20ci/2015/09/21/code-coverage-for-ios-xcode-7/

**Comment by BamX** [comment]
Is there any progress with this task?

**Comment by renep** [comment]
I have added the '-enableCodeCoverage' one week ago, therefor there is progress ;-)

**Comment by renep** [comment]
This one is not so simple as I thought. To get the coverage that is simple, but to get a proper report is not. llvm only has tools to get a simple text report, and I think I will start with this.
But to get a cobertura compatible xml or a nice html report this is not so simple.

I have taken a look at Slather but, I don't think that this is the proper tool to use for various reasons e.g. Slather depends on some xcode build project settings, but the are not needed. 

All we need is a tool that converts the profdata to a cobertura.xml or html, but I have not found one yet. I hope that I don't need to do this myself.

**Comment by renep** [comment]
There is progress: https://github.com/openbakery/CoverageReport
This will be included into the plugin soon.

**Comment by renep** [comment]
fixed with 0.13.0
