### ISSUE TITLE
Entitlements bug in case of InHouse wildcard provisioning profile 

### ISSUE THREAD

**Issue by endrelzr** [openbakery/gradle-xcodePlugin#229]
I had an issue today where the application signing entitlements were created as follows: 

```
<plist version="1.0">
<dict>
    <key>application-identifier</key>
    <string>1A2B3C4D5E.com.mycompany.com.mycompany.appName</string>
    <key>com.apple.developer.team-identifier</key>
    <string>1A2B3C4D5E</string>
    <key>get-task-allow</key>
    <false/>
</dict>
</plist>
```

However the script configuration and the plist files were correct, the app could not be upgraded on the iOS devices while did not match the previous bundle identifier. I used an InHouse provisioning profile with a Wildcard AppId. 
In case of InHouse distribution, as I saw the plugin generated the application-identifier from the provisioning profile's application-identifier key concatenated to the bundleID. As checked our AppStore, InHouse and AdHoc provisioning profiles I would say the entitlement application-identifier should be generated from the teamId concatenated with the appID from the provisioning profile. 
Is this a bug or am I missing something here?

**Comment by renep** [comment]
Looks like a bug. See also https://github.com/openbakery/gradle-xcodePlugin/issues/226#issuecomment-160625859

**Comment by endrelzr** [comment]
I wasn't sure if the 2 cases are directly related. Opened a pull request with a fix. I ran the tests and all passed.
