### ISSUE TITLE
Add bitcode Support

### ISSUE THREAD

**Issue by mathiasnagler** [openbakery/gradle-xcodePlugin#233]
Currently the gradle-xcodePlugin does not seem to have complete support for Bitcode. When exporting an app with Xcode that has bitcode enabled Xcode adds folders `Symbols` and `BCSymbolMaps`. The folders contain `.symbols` and `.bcsmybolmap` files respectively. 

I tried to visualize the issue with a screenshot. The left shows the app exported using Xcode and the right is the version built using gradle.
![comparsion](https://cloud.githubusercontent.com/assets/9951231/11838517/e237c116-a3e7-11e5-889d-ad5b2886e1ec.png)

The missing files are not necessary for the app to run. It seems Apple needs those files to be able to symbolicate crashlogs for apps build with bitcode enabled. For those app there is currently no other way that I know of to receive symbolicated crashlogs.

As bitcode is mandatory for some platforms (watchOS, tvOS) this is a real issue. When targeting those platforms gradle is not really usable for the App Store build as you lose the ability to receive useful crashlogs.

**Comment by tompson** [comment]
I was under the impression that the bitcode symbolication stuff has to be downloaded from Apple after the app is in the Store - at least I had to do this for crashlytics

**Comment by mathiasnagler** [comment]
I don't understand why that would be the case. The files in the screenshot are contained within the ipa that was exported straight from Xcode. Why would it contain files that need to be downloaded from Apple? 
When uploading the ipa to iTunes Connect one would reupload stuff that was downloaded from there in the the first place if that was the case.

**Comment by tompson** [comment]
ok, maybe I misunderstood your question

what I had to deal with in the last weeks was getting Bitcode apps work with Crashlytics. for crashlytics to get all the symbol information it is necessary to download the symbol information from Apple after the processed the uploaded IPA

**Comment by krummler** [comment]
Has this been resolved? I am getting the same problem.

I'm using openbakery 0.14.5 with gradle and am running:

`gradle clean build archive package`

This gives me an .ipa file, but trying to send it to apple using the application loader (3.6) it returns a whole bunch of errors like these:

    ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'MyApp.app/Frameworks/SVProgressHUD.framework/SVProgressHUD' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by renep** [comment]
Not yet, but this is one of the things I will do next.

**Comment by krummler** [comment]
Thanks for the quick reply. This does mean it is currently impossible to use these builds to upload to apple? Or is there maybe some kind of workaround?

If I can help to test I'll be happy to pitch in :).

**Comment by renep** [comment]
You can upload to apple, but you project should not contain any bitcode.
e.g. if you use 3rd Party libs.

When you use cocoapods you can achive this with the following setting in your `Podfile`:
```post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by krummler** [comment]
Thanks, thats what I did for now 👍
