### ISSUE TITLE
Keychain gets not removed from search list

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#234]
When running keychainRemove the current keychain gets not removed!

**Comment by tompson** [comment]
just to get udpdates

**Comment by tompson** [comment]
any updates on this? should I try to look into this? it is really annoying that I have to log into my machine multiple times a day to delete the left over keychains

**Comment by renep** [comment]
Now the current keychain should be removed from the search list at the and of the package task.
Can you please tests. I have created a 0.12.6-TEST version and uploaded it to the openbakery.org repository

**Comment by tompson** [comment]
tried version 0.12.6-TEST but still got 

    :keychainRemove (Thread[Daemon worker Thread 3,5,main]) started.
    :keychainRemove
    Executing task ':keychainRemove' (up-to-date check took 0.0 secs) due to:
      Task has not declared any outputs.
        "/Users/tom/Library/Keychains/login.keychain"
        "/Users/tom/Development/xcodeProjects/myproject/build/codesign/gradle-1453114946144.keychain"
        "/Library/Keychains/System.keychain"
    :keychainRemove (Thread[Daemon worker Thread 3,5,main]) completed. Took 0.014 secs.

**Comment by renep** [comment]
should be fixed with 0.12.7

**Comment by tompson** [comment]
yeah, looks good now, thank you!

**Comment by BamX** [comment]
Why are you removing keychain? I'm using login keychain for signing and I don't want it to be removed.

**Comment by renep** [comment]
You should not use the login keychain. The plugin is designed to create a keychain for every build, that is removed in the end. This is done to make sure that only one key is in the keychain!

**Comment by BamX** [comment]
I have certificates in login.keychain. There is no information about I can't use them for signing. Do you say I have to export my certificates somewhere or create different keychain?

**Comment by renep** [comment]
The idea is that you export the key as p12 and specify the key with:
```
signing {
  certificateURI = file:///path-to-the-p12
  certificatePassword = 'password-for-the-p12'
}
```

During the build a keychain is created with this p12 that is then used.
For example I have the p12 files in my network in a single location and if a certificate changes I only have to update it there. All machine that can build the app (e.g. build nodes) have access to this location and can fetch the certification. So I do not have to update the keychains manually on every box.
Get the idea?
(Same applys to the provisioning profiles)

**Comment by BamX** [comment]
That make sence. Thank you!
