### ISSUE TITLE
Building a command line tool fails

### ISSUE THREAD

**Issue by andysgn** [openbakery/gradle-xcodePlugin#235]
When I run the plugin on a command line app (create a command line tool from xcode), I get this error:

Execution failed for task ':infoplistModify'.
> No Info.plist was found! Check you xcode project settings if the specified target has a Info.plist set.

Is there a way around this?

**Comment by renep** [comment]
I have not tried this plugin with a command line tool.
You can try and set a dummy value for the info plist, so that the build does not get skipped.
e.g.
```
xcodebuild {
  infoPlist = "dummy.plist"
}
```

**Comment by BamX** [comment]
Check $(SDKROOT) in Info.plist property of your project.

**Comment by renep** [comment]
There is no info.plist for a command line tool.
