### ISSUE TITLE
Unittest problem xcode7.2 OS X 10.11

### ISSUE THREAD

**Issue by kolard** [openbakery/gradle-xcodePlugin#236]
Hi
I've faced strange issue with unit tests.
If I run tests via CMD

     xcodebuild -workspace my.xcworkspace -scheme my_-QA -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" test

all works ok.

If I run same task via gradle and xcode plugin with same config

        if (taskGraph.hasTask(test)) {
                println "Configure device settings for the build and unit tests"

                println "Setting xcodebuild configuration"
                xcodebuild {
                                version = "7"
                                type = 'ios'
                                simulator = true
                                target = 'UnitTesting'
                                scheme = 'My-QA'
                                workspace = 'My.xcworkspace'
                                configuration = 'Debug'
                                destination {
                                        platform = 'iOS Simulator'
                                        name = "${device}"
                                        os="${ios}"
                                }
                        }
                }

Than I see error like 

    0 tests completed

    0 tests were successful, and 0 failed
    :xcodetest FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':xcodetest'.
    > java.lang.Exception: Not all unit tests are successful!

1) Can be that problem in old ruby Gems? Cos many problems were resolved just after update gems like run_loop.
2) Which gems gradle uses for running unit tests via xcode? And what versions of this gems should I use?

Thank you.

P.S I've tried 2 xcode plugin versions: latest and 0.11.6.

**Comment by renep** [comment]
First, there are no gems needed, because the plugin is not writting in ruby ;-)

To investigate this you can run the gradle test target with '--debug' then you should see a lot of output, and also the xcodebuild command that is executed for running unit tests.

I don't know if this is the problem, but the target should not be the unit test target, I always use the application target.

**Comment by kolard** [comment]
We've investigated debug logs with dev team, and didn't see anything "interesting"
I'll try with another target. 
Thanks.

**Comment by kolard** [comment]
I've found one possible issue. Here is command from output with debug

    16:28:38.477 [DEBUG] [org.openbakery.CommandRunner] Run command: 'script -q /dev/null /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -scheme JohnLewis_JL -workspace JohnLewis.xcworkspace -configuration Debug -derivedDataPath ...  -destination platform=iOS Simulator,id=1A85F110-E4F1-494B-B14C-24301015D196 test'

looks like parameters for -destination should be in quotes

    ...  -destination "platform=iOS Simulator,id=1A85F110-E4F1-494B-B14C-24301015D196" test

I've try to run this manually and only command with quotes works.

**Comment by renep** [comment]
Nope, quotes can't be the problem here. The quotes are not shown in the output.
If they were, it would not work on my machine, but it does.

**Comment by kolard** [comment]
Hm.
I haven't any idea why it works with cmd and not woth gradle. We tested on 5 mac's.

**Comment by renep** [comment]
Can you try to clone this project and navigate into `example/iOS/Example` and run `gradle test`?

Output should be this:
```
:xcodebuildConfig
:simulatorKill
:xcodetest

Run tests for: iPad 2/iOS Simulator/9.2
1 tests completed

Run tests for: iPhone 4s/iOS Simulator/9.2
1 tests completed

All 2 tests were successful
:test

BUILD SUCCESSFUL

Total time: 57.225 secs

This build could be faster, please consider using the Gradle Daemon: https://docs.gradle.org/2.8/userguide/gradle_daemon.html
```

**Comment by kolard** [comment]
Yes. I've tried and "gradle test" works with your example project.
Do you have any ideas what can be wrong with our project? Looks like (via gradle) xcode only builds project and doesn't run tests. But same command in CMD works good.

**Comment by renep** [comment]
Difficult do say...
Are you sure that the commands are identical (except if the quotes)

Maybe there is a problem installing the app in the simulator. Maybe try `gradle simRun` and see if the app in the simulator launches.
You can also try to recreate all simualtors by running `gradle simCreate`.

You can also have a look in the simulator log files if you find something: `~/Library/Logs/CoreSimulator/<device id>/system.log`
You find the device Id with `gradle simList`

**Comment by kolard** [comment]
Thanks.
I'll look into sim logs. 
Application on sim works, cos another tests ( runs with calabash ) works ok. But calabash uses ruby gems for run simulators and install app there.
