### ISSUE TITLE
How to export dSYM file?

### ISSUE THREAD

**Issue by wangqianjun** [openbakery/gradle-xcodePlugin#237]
Hi, openbakery
How to export dSYM file ?

**Comment by renep** [comment]
What do you mean?

**Comment by wangqianjun** [comment]
I  need dSYM file positioning crash for my APP. so how to export dSYM file use gradle-xcodePlugin?

**Comment by renep** [comment]
When you build your app you first run 'gradle archive' to create your xcarchive, and then you run 'gradle package' to create the ipa that can be installed on the device.
The 'archive' task creates a xcarchive and this includes the dsym.
You also find the dsym in the 'build/sym/' directory.

**Comment by wangqianjun** [comment]
ok,I got it,  Thank u !
