### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by wangqianjun** [openbakery/gradle-xcodePlugin#239]
Hi, bakery, 
I had an issue today where the application build  as follows:

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'YH_Mall'.
  > Could not resolve all dependencies for configuration ':classpath'.
  > Could not resolve gradle.plugin.org.openbakery:xcode-plugin:0.12.5.
   Required by:
       :YH_Mall:unspecified
    > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/org/openbakery/xcode-plugin/0.12.5/xcode-plugin-0.12.5.pom'.
       > peer not authenticated

Is this a bug or am I missing something here?

**Comment by renep** [comment]
Maybe a problem with the plugins.gradle.org site.

You can try and use my repo with following in your build.gradle:
```
buildscript {
	repositories {
		maven {
			url('http://repository.openbakery.org')
		}
		mavenCentral()
  }

	dependencies {
	    classpath "org.openbakery:xcode-plugin:0.12.+"
	}
}

apply plugin: 'org.openbakery.xcode-plugin'
```
