### ISSUE TITLE
Unable to configure xcodebuild.productName

### ISSUE THREAD

**Issue by eseilnacht** [openbakery/gradle-xcodePlugin#240]
I am trying configure the Info.plist CPFBundleName and CPFBundleDisplayName.  

13:25:39.271 [QUIET] [system.out] project.xcodebuild.configuration: Release
13:25:39.271 [QUIET] [system.out] project.xcodebuild.type: iOS
13:25:39.271 [QUIET] [system.out] project.xcodebuild.target: MBankPhone
13:25:39.272 [QUIET] [system.out] project.xcodebuild.infoPlist: MBankPhone/Info.plist
13:25:39.272 [QUIET] [system.out] project.xcodebuild.productName: My_Bank
13:25:39.273 [QUIET] [system.out] project.infoplist.bundleName: My_Bank

The build works but then fails during the archive task it fails to find the app:

13:28:25.631 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:exec] ditto: can't get real path for source 'xxx/build/sym/Release-iphoneos/My_Bank.app'
13:28:25.632 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':archive'
13:28:25.632 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :archive FAILED

I think this is due to the fact that the productName is still ${TARGET} which is MBankPhone.  The app is actually under 'xxx/build/sym/Release-iphoneos/MBankPhone.app'.

Is there something I can do to set the CPFBundleName to something other that the target ?

erik-seilnacht-2:~ erik.seilnacht$ gradle --version

---
## Gradle 2.3

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_21 (Oracle Corporation 23.21-b01)
OS:           Mac OS X 10.10.5 x86_64

**Comment by renep** [comment]
Normally the CFBundleName is uses to get the name of the App in the sym/Release-iphoneos directory. 

In your case, you can set the value use with an undocumented parameter:

```
xcodebuild {
  bundleName = 'My_Bank'
}
```

Then it `sym/Release-iphoneos/My_Bank.app` should be used.

**Comment by eseilnacht** [comment]
I tried setting the xcodebuild.bundleName but it still produced an app using the target name.

14:33:11.684 [QUIET] [system.out] project.xcodebuild.target: MBankPhone
14:33:11.685 [QUIET] [system.out] project.xcodebuild.infoPlist: MBankPhone/Info.plist
14:33:11.686 [QUIET] [system.out] project.xcodebuild.bundleName: Crazy_App
14:33:11.687 [QUIET] [system.out] project.xcodebuild.productName: Crazy_App
14:33:11.688 [QUIET] [system.out] project.infoplist.bundleName: Crazy_App

14:36:06.243 [INFO] [org.openbakery.CommandRunner] Validate build/sym/Release-iphoneos/MBankPhone.app
14:36:06.243 [INFO] [org.openbakery.CommandRunner]     cd /Users/erik.seilnacht/Desktop/temp/MBankPhone
14:36:06.243 [INFO] [org.openbakery.CommandRunner]     export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/opt/subversion/bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/mysql/bin:/Applications/android-sdk-macosx/tools/:/Applications/android-sdk-macosx/platform-tools/:/Development/mongodb-osx-x86_64-2.2.2/bin:/usr/local/squid/sbin:/usr/share/ant/bin:/Applications/HP_Fortify/HP_Fortify_SCA_and_Apps_3.80/bin:/Development/gradle-2.3/bin:/Development/apache-maven-3.3.3/bin"
14:36:06.244 [INFO] [org.openbakery.CommandRunner]     export PRODUCT_TYPE=com.apple.product-type.application
14:36:06.244 [INFO] [org.openbakery.CommandRunner]     builtin-validationUtility /Users/erik.seilnacht/Desktop/temp/MBankPhone/build/sym/Release-iphoneos/MBankPhone.app -validate-for-store
14:36:06.244 [INFO] [org.openbakery.CommandRunner] 
14:36:06.257 [INFO] [org.openbakery.CommandRunner] ** BUILD SUCCEEDED **

14:36:06.322 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:exec] ditto: can't get real path for source '/Users/erik.seilnacht/Desktop/temp/MBankPhone/build/sym/Release-iphoneos/Crazy_App.app'
14:36:06.323 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':archive'
14:36:06.323 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :archive FAILED

erik-seilnacht-2:~ erik.seilnacht$ ls /Users/erik.seilnacht/Desktop/temp/MBankPhone/build/sym/Release-iphoneos/ | grep "\.app"
MBankPhone.app
MBankPhone.app.dSYM

My concern is that this may show up somewhere on iOS but I've read conflicting things about that.

http://stackoverflow.com/questions/12146750/where-cfbundlename-is-being-used

If it will not ever show up then I will leave it as is and just allow customization of the CFBundleDisplayName.

**Comment by renep** [comment]
The xcodebuild.bundleName does not change the bundle name. This value is only used to identify the application bundle when the archie is created by this plugin.
This is only an internal value, therefor is is not documented, at least it is intended only as internal value.
Normally this value is fetched from info plist settings, but you can have a variable here like `${TARGET}` that is not evaluated. (Only `{PRODUCT_NAME}`, `{SRC_ROOT}` and `{TARGET_NAME}` are)  Therefor you can manually set it.
The best way here would be that I support all the possible options, but they are not obvious in the first place.
