### ISSUE TITLE
Create task that runs 'pod update' 

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#241]
Create a tasks that updates the pods

**Comment by adil-hussain-84** [comment]
Thanks for creating this task @renep. I wish I had the Gradle know-how to add it myself :-( Would be great to have the `pod update` happen as part of the `gradle build` task.

Also, would be great whoever can add it to be aware of the following issue in the Gradle Cocoapods plugin:

https://github.com/x2on/gradle-cocoapods-plugin/issues/5

**Comment by renep** [comment]
fixed with 0.13.0

**Comment by adil-hussain-84** [comment]
Awesome! Thanks so much @renep! :+1:

**Comment by adil-hussain-84** [comment]
I see that the `cocoapodsUpdate` task actually does a `pod install`. I guess it still has the desired effect of updating pods but the name is a bit misleading.

**Comment by renep** [comment]
Log output is wrong here, when you run with `--debug` than you should see what really executed.
I have updated the log output
