### ISSUE TITLE
Coverage outputFormat should support more than 1 format simultaneously 

### ISSUE THREAD

**Issue by Nathan-Smith** [openbakery/gradle-xcodePlugin#246]
According to the Parameters doc coverage can only be configured to output either text, html **or** xml. It can be useful in CI to generate both html and xml simultaneously so the html can be served as an artifact and the xml is used for something like Sonarqube.

**Comment by renep** [comment]
With the upcoming CoverageTask changes it should be possible to define own task of the CoverageTask type in you build.gradle file, an this should then be possible.

**Comment by jaredsburrows** [comment]
👍

**Comment by renep** [comment]
Here I want to extend that the coverage task could be executed twice by defining a own task (similar to gradles copy task)
