### ISSUE TITLE
How to access provisioning profile set as environment variable in gradle.properties file

### ISSUE THREAD

**Issue by Aswini999** [openbakery/gradle-xcodePlugin#248]
Here is my gradle.properties file

```bash

prov_profile=System.getenv("PROV_PROFILE")
cert_source=System.getenv("CERT_SOURCE")
cert_pwd=System.getenv("CERTIFICATE_PWD")

MyApp.Release.SigningCertificate=cert_source
MyApp.Release.SigningCertificatePassword=cert_pwd
MyApp.Release.SigningMobileProvision=prov_profile

MyApp.Debug.SigningCertificate=/Users/myuser/DEV_CFTS/Developer.p12
MyApp.Debug.SigningCertificatePassword=secret
MyApp.Debug.SigningMobileProvision=/Users/myuser/DEV_CFTS/Developer.mobileprovision
```
When i try to access MyApp.Release.SigningCertificate in build.gradle, file path is replaced as '<Working Directory>/Sysem.getenv("PROV_PROFILE")'

Kindly suggest further..

**Comment by renep** [comment]
The gradle.properties is no DSL, only key value pairs are valid there. You need to put the `MyApp.Release.SigningCertificate=System.getenv("PROV_PROFILE")` in your build.gradle file.
Or you can pass properties via command line with `-D` or `-P` see: https://docs.gradle.org/current/userguide/build_environment.html

**Comment by Aswini999** [comment]
Thanks for the info @renep
