### ISSUE TITLE
test-wildcard-mac-development Provisioning Profile expired

### ISSUE THREAD

**Issue by icecrystal23** [openbakery/gradle-xcodePlugin#249]
Hi there.  I'm trying to start building my fork on travis, but I'm running into failing tests because the example app profile is expired:
test-wildcard-mac-development

**Comment by renep** [comment]
I think you should merge the develop branch, because I have this this there:
see also: https://travis-ci.org/openbakery/gradle-xcodePlugin

**Comment by icecrystal23** [comment]
Cool, it is working on the develop branch.  Thanks.
