### ISSUE TITLE
provisioningInstall and bundling failed for valid certificate and profiles

### ISSUE THREAD

**Issue by Aswini999** [openbakery/gradle-xcodePlugin#250]
Below is the log while executing gradle task
```bash
provisioningClean
:provisioningInstall
No provisioning profile specifed so do nothing here
:cocoapods
:xcodebuildConfig
:infoplistModify
:xcodebuild
Done
:archive
:keychainClean
:keychainCreate
:package
No certificate or keychain found.
No provisioning profile found for bundle identifier com.ikea.ikeacatalogue2
Available bundle identifier are []
Bundle not signed: /Users/myuser/<project_folder>/build/package/Payload/MyApp.app
:keychainRemove
:package/MyApp/Release
:release
```

I'm able to print certificates and  provisioning profile paths while executing task but 'No provisioning profile specifed so do nothing here' message for provisioningInstall

**Comment by renep** [comment]
It looks like that the provision profile file does not exist, therefor it is not read.
The output
```
No provisioning profile specifed so do nothing here
```
Tells you that you do not have specified any provisiong profile, therfor it is valid that nothing is signed.

**Comment by Aswini999** [comment]
Yes. my mistake. Forgot to convert to URI.
