### ISSUE TITLE
mobileprovision entitlements expansion

### ISSUE THREAD

**Issue by eseilnacht** [openbakery/gradle-xcodePlugin#252]
Hello,

I have a provisioning profile used for development that contains a wildcard for the 'application-identifier'

eg:

```
    <key>application-identifier</key>
    <string>ABCDE12345.com.orgname.enterprise.*</string>
    <key>com.apple.developer.ubiquity-kvstore-identifier</key>
    <string>ABCDE12345.*</string>
```

My project.infoplist.bundleIdentifier in this example is set to 'com.orgname.enterprise.adhoc.digital'

The expansion that is (presumably) taking place in signing.ProvisioningProfileReader is causing the output to be:

ABCDE12345.com.orgname.enterprise.com.orgname.enterprise.adhoc.digital

This is causing problems for me later on.

Given the com.apple.developer.ubiquity-kvstore-identifier is 'ABCDE12345.*', it expands correctly:

ABCDE12345.com.orgname.enterprise.adhoc.digital

Presumably because the code below is maybe expanding and \* with the bundleIdentifier.

`   void extractEntitlements(File entitlementFile, String bundleIdentifier) {
        String entitlements = commandRunner.runWithResult([
                        "/usr/libexec/PlistBuddy",
                        "-x",
                        getPlistFromProvisioningProfile().absolutePath,
                        "-c",
                        "Print Entitlements"])
        FileUtils.writeStringToFile(entitlementFile, entitlements.toString())

```
    setBundleIndentiferToEntitlementsForValue(entitlementFile, bundleIdentifier, "application-identifier")
    setBundleIndentiferToEntitlementsForValue(entitlementFile, bundleIdentifier, "com.apple.application-identifier")
    setBundleIndentiferToEntitlementsForValue(entitlementFile, bundleIdentifier, "com.apple.developer.ubiquity-kvstore-identifier")
    //setBundleIndentiferToEntitlementsForValue(entitlementFile, bundleIdentifier, "keychain-access-groups")

    // the keychain-access-groups were removed from the entitlements on the xcode export step
    // therefor I also remove this here. Maybe this is wrong, but I hope the future will clarify this.
    //plistHelper.deleteValueFromPlist(entitlementFile, "keychain-access-groups")



}

private void setBundleIndentiferToEntitlementsForValue(File entitlementFile, String bundleIdentifier, value) {
    def currentValue = plistHelper.getValueFromPlist(entitlementFile, value)

    if (currentValue == null) {
        return
    }

    if (currentValue instanceof List) {
        def modifiedValues = []
        currentValue.each { item ->
            if (item.toString().endsWith('*')) {
                modifiedValues << item[0..-2] + bundleIdentifier
            }
        }
        plistHelper.setValueForPlist(entitlementFile, value, modifiedValues)

    } else {
        if (currentValue.toString().endsWith('*')) {
            plistHelper.setValueForPlist(entitlementFile, value, currentValue[0..-2] + bundleIdentifier)
        }
    }
}`
```

Is there something wrong with my config?
## Gradle 2.3

Build time:   2015-02-16 05:09:33 UTC
Build number: none
Revision:     586be72bf6e3df1ee7676d1f2a3afd9157341274

Groovy:       2.3.9
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.7.0_21 (Oracle Corporation 23.21-b01)
OS:           Mac OS X 10.10.5 x86_64

classpath group: 'org.openbakery', name: 'xcode-plugin', version: '0.12.4'

Thank you

**Comment by renep** [comment]
I don't get what your problem is.
What modification is not correct? What should not be expanded?

**Comment by eseilnacht** [comment]
I thinking expecting that the 'application-identifier':

ABCDE12345.com.orgname.enterprise.*   would expand to ABCDE12345.com.orgname.enterprise.adhoc.digital

And not to:

ABCDE12345.com.orgname.enterprise.com.orgname.enterprise.adhoc.digital

This is causing trouble for during data migration between app versions, since our previous apps have the 'application-identifier' as ABCDE12345.com.orgname.enterprise.adhoc.digital

But maybe I'm missing something about how wildcarding should work in this case.

Thanks

**Comment by renep** [comment]
Looks like a bug, because
`ABCDE12345.com.orgname.enterprise.com.orgname.enterprise.adhoc.digital` is not the intended result.

**Comment by eseilnacht** [comment]
I added a task to modify the entitlements.plist after the package task and then repackage the ipa.  Will keep an eye out for a fix.

Thanks
