### ISSUE TITLE
xcodebuild: error when building new target/scheme created through Command line

### ISSUE THREAD

**Issue by Aswini999** [openbakery/gradle-xcodePlugin#255]
I have created new target for calabash-ios using `calabash-ios setup`. New scheme and target are created. I can see the calabash scheme in schemes list. But xcodebuild failed.

Error Message: 
```
xcodebuild: error: The workspace named "DemoApp" does not contain a scheme named "DemoApp-cal". The "-list" option can be used to find the names of the schemes in the workspace.
```
Kindly Suggest.

**Comment by Aswini999** [comment]
Fixed this error by scripting for xcodebuild

**Comment by syntetikvision** [comment]
Aswini9999 how did you fix this error ? Can you please share your solution. 

Best regards,
