### ISSUE TITLE
Run unit tests without device or simulator

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#258]
After running the example and reading: https://github.com/openbakery/gradle-xcodePlugin/blob/master/Documentation/Parameters.md#unit-test-settings, it looks like there is no way to run regular "logic" unit tests without the simulator.

See here: http://stackoverflow.com/questions/19219706/xcode-5-unit-testing-starts-my-app.

**Comment by renep** [comment]
I have run a test with a framework that has unit tests. Here no app is launched in the simulator, but the simulator itself is launched. I have not investigated it further, but I found no quick way to avoid the simulator launch when running the unit tests for an iOS target.

You can use a mac os x target, than no simulator should be launched.

**Comment by jaredsburrows** [comment]
@renep Do you have an example?

**Comment by jaredsburrows** [comment]
@renep  Is this what you mean?
```
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' } // Mirrors jcenter() and mavenCentral()
        maven { url 'http://repository.openbakery.org/' }
    }

    dependencies {
        classpath 'org.openbakery:xcode-plugin:0.13.0'
    }
}

apply plugin: 'org.openbakery.xcode-plugin'

xcodebuild {
    scheme = 'ios-gradle-objc-template'
    target = 'ios-gradle-objc-template'

    configuration = 'Debug'
    simulator = false

    destination {
        platform = 'OSX'  // <-- Is this what you mean?
    }

    coverage {
        outputFormat = 'html'
        exclude = '.*h$|.*UnitTests.*m$'
    }
}
```

**Comment by jaredsburrows** [comment]
@renep Is this possible or not? Should I just close this?

**Comment by renep** [comment]
I think when you have a framework that also runs on macOS this should be possible. I have not tested this yet so I don't know if the plugin can run this without any modification.
You can keep this issue open as reminder for now, because this would be a good improvement.

**Comment by jaredsburrows** [comment]
Similar to "androidTests", you have to run tests on the emulator.
