### ISSUE TITLE
WatchKitSupport Folder not created

### ISSUE THREAD

**Issue by mathiasnagler** [openbakery/gradle-xcodePlugin#259]
I have an app that contains a WatchKit App. When I create an App Store build using the current version of `gradle-xcodePlugin` (`0.13.0`) and upload the build to iTunes Connect I receive a mail from Apple:

```
Invalid WatchKit Support - The WatchKitSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.
```

Upon inspecting the `WatchKitSupport` folder seems to be missing indeed. I _think_ there should be a `WatchKitSupport` folder in the `ipa` containing a copy of `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/Library/Application\ Support/WatchKit/WK`.

Is this a known issue?

**Comment by renep** [comment]
No, thats a new one.
This one should be similar to adding the swift support folder.

**Comment by mathiasnagler** [comment]
Ok. A colleague and I will try to fix this and create a PR. We will come back at you later.
