### ISSUE TITLE
Invalid SwiftSupport when using Frameworks

### ISSUE THREAD

**Issue by mathiasnagler** [openbakery/gradle-xcodePlugin#260]
I have an app that does not contain any Swift code. It does, however, contain a dependency integrated as a precompiled `.framework`. When building, this will be copied to `build/sym/XXX-iphoneos/YYY.app/Frameworks`. This results in a `SwiftSupport` folder being created when packaging the app.

The workaround from #242 does not work in this case, as the `Frameworks` folder is not empty. I *think* it is not safe to rely on wether `Frameworks` has any contents when fixing the `invalid SwiftSupport` issue. 

What do you think about this? Is this something I am misinterpreting?

**Comment by renep** [comment]
Hmm, good point. The question here is: Who do I detect that the SwiftSupport must be added? So, how do I know if this project contains swift code?

Let me google that ;-)

**Comment by renep** [comment]
Ok, if there is a SwiftSupport in the xcarchive, there should be SwiftSupport also in the package. If not, than the SwiftSupport should be skipped.

**Comment by renep** [comment]
The problem here as it looks is not the package task it is the archive that adds the SwiftSupport stuff.
