### ISSUE TITLE
Kill simulator after running tests

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#262]
The plugin should kill the simulator after the tests.

This way, we do not have to do this:

```
script:
 - ./gradlew clean assemble test --stacktrace

after_script:
 - ./gradlew simulatorKill
```

**Comment by renep** [comment]
You can achive this with a finalizer task:
https://docs.gradle.org/current/userguide/more_about_tasks.html#N11385
