### ISSUE TITLE
Move outputs of Cpd, OCLint and Gcovr to '/build/reports'

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#263]
Move outputs of Cpd, OCLint and Gcovr to '/build/reports' similar to other plugins:
https://github.com/kt3k/coveralls-gradle-plugin/blob/master/src/main/groovy/org/kt3k/gradle/plugin/CoverallsPluginExtension.groovy#L23

**Comment by renep** [comment]
Good point, and this should also be an easy one

**Comment by jaredsburrows** [comment]
Would you accept a PR for this?

**Comment by renep** [comment]
Yes

**Comment by jaredsburrows** [comment]
@renep If this is fixed, we can close this?
