### ISSUE TITLE
Rename 'org.openbakery:xcode-plugin' to 'org.openbakery.xcode.tools.build:gradle'

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#265]
Similar to the naming of the Android build tools(see [here](https://bintray.com/android/android-tools/com.android.tools.build.gradle/view)): `com.android.tools.build:gradle:2.0.0`.

Can we rename this plugin to: `org.openbakery.xcode.tools.build:gradle:0.13.0`?

**Comment by renep** [comment]
This is worth considering. I will think about it.
I have to change the plugin to the new gradle rules model system, which would be a great benefit, but I have not found time etc to start with this. (But in the near future I will do some refactorings to get this on the way)
With the new rules model system I don't thing that the plugin is backwards compatible with the current version and at this point a renaming could be a good choice.

**Comment by jaredsburrows** [comment]
👍

**Comment by jaredsburrows** [comment]
@renep Would you accept a PR for this?

**Comment by renep** [comment]
No. The reason is that changing the id would brake backward compatibility and every user that uses this plugin has to modify the build.
Changing the ID make only sense, when a also some other braking change is done in the plugin.
Als a mentioned above, this could be the case then I do the rules modle system.

**Comment by jaredsburrows** [comment]
@renep Since you said no, should we close this? First you said you would consider it but should we just close this issue now?

**Comment by renep** [comment]
I said no for now. When I do a braking change in the plugin, then it is ok to rename the plugin. There keep this issue open as a reminder.

**Comment by jaredsburrows** [comment]
Sounds good. Thanks.
