### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by gab-horv** [openbakery/gradle-xcodePlugin#268]
Hi,

Today my builds failed with this log:

* What went wrong:
A problem occurred configuring root project 'MyProject-build'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve org.openbakery:xcodePlugin:0.9.+.
     Required by:
         :MyProject-build:unspecified
      > Failed to list versions for org.openbakery:xcodePlugin.
         > Could not list versions using M2 pattern 'http://openbakery.org/repository/[organisation]/[module]/[revision]/[artifact]-[revision](-[classifier]).[ext]'.
            > Could not GET 'http://openbakery.org/repository/org/openbakery/xcodePlugin/'.
               > hostname in certificate didn't match: <openbakery.org> != <*.azurewebsites.net> OR <*.azurewebsites.net> OR <*.scm.azurewebsites.net> OR <*.azure-mobile.net> OR <*.scm.azure-mobile.net>

Last week same build was ready.

Could you help me?

Thanks!

**Comment by renep** [comment]
Use `http://repository.openbakery.org` as url instead of `http://openbakery.org/repository` because I have moved the website to Azure.
Or use official gradle plugins settings: https://plugins.gradle.org/plugin/org.openbakery.xcode-plugin

**Comment by gab-horv** [comment]
New url is working, thank you for your quick reply!
