### ISSUE TITLE
Broken AdHoc builds, incorrect code signing

### ISSUE THREAD

**Issue by AlexanderKhudyakov** [openbakery/gradle-xcodePlugin#270]
Hello, I'm trying to build adhoc, but no luck so far. "gradle archive package" does the job without any errors, but output *.ipa won't install on any of my devices. 
Error message on install is
`May 23 19:39:31 iPad atc[864] <Error>: 0x16e58f000 __MobileInstallationInstallForLaunchServices_block_invoke222: Returned error Error Domain=MIInstallerErrorDomain Code=13 "Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.KJ5SAH/extracted/Payload/MyProject.app : 0xe8008016 (The executable was signed with invalid entitlements.)" UserInfo={LibMISErrorNumber=-402620394, LegacyErrorString=ApplicationVerificationFailed, SourceFileLine=142, FunctionName=+[MICodeSigningVerifier _validateSignatureAndCopyInfoForURL:withOptions:error:], NSLocalizedDescription=Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.KJ5SAH/extracted/Payload/MyProject.app : 0xe8008016 (The executable was signed with invalid entitlements.)}`

My script looks like this:

```
plugins {
     id "org.openbakery.xcode-plugin" version "0.13.1"
}
xcodebuild {
    scheme = 'MyProject'
    target = 'MyProject'
    configuration = 'Release'
    simulator = false
    signing {
        mobileProvisionURI = [new File('MyProject_CodeSigning/MyProjectDistribution.mobileprovision').toURI(), new File('MyProject_CodeSigning/MyProjectExtensionDistribution.mobileprovision').toURI(), new File('MyProject_CodeSigning/MyProjectWidgetDistribution.mobileprovision').toURI()]
        certificateURI = new File('MyProject_CodeSigning/Distribution.p12').toURI()
        certificatePassword = 'SoSecretVerySafeVowMuchPassword'
  }
}
```

So, is it a bug of some kind, or I'm doing something wrong?

**Comment by AlexanderKhudyakov** [comment]
I have tried almost everything, adhoc build doesn't install. If I use basic Xcode workflow (e.g archive - > export adhoc), everything is fine.

My app has an extension and a widget. There is also an *.entitlement with iCloud storage enabled.

**Comment by renep** [comment]
Can you compare the entitlements from the build that is created with Xcode and using gradle. You can see the entitlements values when you extract the IPA and then use this command:
```codesign -d --entitlements :- Payload/MyProject.app```

**Comment by AlexanderKhudyakov** [comment]
Yes, result are different.
Here's the diff: [http://content.screencast.com/users/al.khudyakov/folders/Jing/media/63856357-7380-4062-a1d6-4d4d0f879816/00000026.png](url)

**Comment by renep** [comment]
The Link does not work. You can send me the image via mail: rene@openbakery.org

**Comment by renep** [comment]
Can you compare the settings that you have in Xcode at your Target at the Capabilities if they are equal to the App ID Settings in the member center where you configure the App Id and Provisioning Profile.

**Comment by AlexanderKhudyakov** [comment]
I see only one difference. In AppCenter AppId settings iCloud pin is yellow and saying that CloudKit enabled but no containers configured. In Capabilities tab in the Xcode project settings only key-value storage is enabled.

**Comment by AlexanderKhudyakov** [comment]
I have fixed the iCloud warning in member center, renewed App ID settings and reissued all provision profiles. Same result here.
[Here](http://content.screencast.com/users/al.khudyakov/folders/Jing/media/f4cc0de5-bbb3-47e8-9f4f-a6dfda3e955e/00000027.png) is the diff of entitlements from adhoc builds generated by xcode and gradle.
Left side is Xcode (working), Right is gradle (not working).
As you can see, gradle-generated entitlements contains much more info.

I have no idea what's happening. Maybe you have any suggestions?

**Comment by niting007** [comment]
Hi guys,
do you got solution?
i am facing same issue..

**Comment by AlexanderKhudyakov** [comment]
Yep. there IS the solution. Check out https://github.com/fastlane/fastlane

**Comment by renep** [comment]
For now I have added a parameter that a custom entitlements file can be specified that is used for signing. Here you must create this file manually with the proper content.
The goal in the long run should be that, that this entitlements is generated automatically, and here the entries from the mobile provisioning profile and some xcode settings must be merged. 

You will get a version with the parameter when my build pipeline has published a new develop version in a few minutes (Version  0.14.2.309.develop or higher)
See also: https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version
and
https://github.com/openbakery/gradle-xcodePlugin/blob/develop/Documentation/Parameters.md#optional-parameters
