### ISSUE TITLE
Plugin not compatible with gradle 2.14

### ISSUE THREAD

**Issue by gounthar** [openbakery/gradle-xcodePlugin#275]
I've just downloaded your example project to see why mine was not building.
I get the same error:

> No service of type ProgressLoggerFactory available in ProjectScopeServices.
------------------------------------------------------------
Gradle 2.14
------------------------------------------------------------

Build time:   2016-06-14 07:16:37 UTC
Revision:     cba5fea19f1e0c6a00cc904828a6ec4e11739abc

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_60 (Oracle Corporation 25.60-b23)
OS:           Mac OS X 10.11.5 x86_64

Xcode version: 7.3.1 (7D1014)

**Comment by jaredsburrows** [comment]
I am seeing the same thing. More information here: https://github.com/openbakery/gradle-xcodePlugin/issues/276.

**Comment by renep** [comment]
The problem here is that the classed for the progress logging and colored logging in gradle itself where moved to a different package. Therefor the next version of the plugin depends on gradle 2.14 or higher, and does not work with older versions anymore.

**Comment by jaredsburrows** [comment]
@renep Can you upgrade this?

**Comment by renep** [comment]
Already implemented in the develop branch and you can use it with: https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

**Comment by gounthar** [comment]
Thanks a bunch.
