### ISSUE TITLE
Add Coveralls

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#277]
@renep Turn on coverralls and I can send a PR for gradle and the badge in the README.md.

**Comment by renep** [comment]
I have recently added a new code coverage support, that uses the new llvm tools. I have created a Coverage tool for this, and here a Coveralls output can be added and then we have Coveralls support here

**Comment by jaredsburrows** [comment]
I am talking about coverage for this repo specifically, for the plugin itself.

**Comment by renep** [comment]
Ah ok. You are right this whould be nice. I think that the coverage is not that bad ;-)

**Comment by renep** [comment]
Here we go: https://coveralls.io/github/openbakery/gradle-xcodePlugin

**Comment by jaredsburrows** [comment]
Do you mind if I send in a PR for the badge?

**Comment by renep** [comment]
see https://github.com/openbakery/gradle-xcodePlugin/tree/develop
