### ISSUE TITLE
Add example projects to CI

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#280]
@renep I just realized that the CI is not building the test apps. See https://github.com/openbakery/gradle-xcodePlugin/issues/264.

We a new structure, this will allow us to build all the modules of the project.

**Comment by renep** [comment]
That is not the case. I have an internal build server thy build all examples on every commit! All is green on my go.cd server.

**Comment by jaredsburrows** [comment]
@renep Update your gradle to the latest and it will fail.
