### ISSUE TITLE
Use Spock Groovy Testing Framework

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#281]
A popular framework for unit testing is Spock for Groovy, see here: https://github.com/spockframework/spock

**Comment by renep** [comment]
I use already Spock when you take a closer look.

**Comment by jaredsburrows** [comment]
You have spock as a dependency: https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/build.gradle#L67.

You do not use it in all of your tests, you assert with `hamcrest`: https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/test/groovy/org/openbakery/oclint/OCLintTaskTest.groovy#L73.
