### ISSUE TITLE
Use normal Intellij Spaces and Fomatting

### ISSUE THREAD

**Issue by jaredsburrows** [openbakery/gradle-xcodePlugin#282]
@renep Upon opening this project for the first time, I noticed everything is using tabs. It would be nice to use the default spacing and formatting of Intellij.

**Comment by jaredsburrows** [comment]
@renep Do you mind if I fix this?

**Comment by renep** [comment]
Spaces. Nooooooo

**Comment by jaredsburrows** [comment]
You are really not open to any new ideas. Look how bad this looks and is really difficult to read: https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/oclint/OCLintTask.groovy#L32.

**Comment by renep** [comment]
The discussion about spaces vs. tabs has nothing to do about being not open to about new ideas. 
I do not want a discussion about this topic. 
I use tabs and this code looks nice in my IDE.

**Comment by jaredsburrows** [comment]
Ok.
