### ISSUE TITLE
Swift libraries duplication

### ISSUE THREAD

**Issue by bamx23** [openbakery/gradle-xcodePlugin#284]
Plugin v0.13.1 builds ipa with SwiftSupport directory in root and Payload/Frameworks directory contains the same libraries.

Xcode (7.3.1) makes ipa files without SwiftSupport directory (only Frameworks).

**Comment by renep** [comment]
I have seen the duplication myself already and I want to investigate this.

The SwiftSupport must be included in the AdHoc builds, but not in the Appstore builds. I have already addressed this in the current develop branch.

I will also investigate is something has changed with Xcode 8.

**Comment by sameoldmadness** [comment]
> I have already addressed this in the current develop branch.

Can you please give a hint when it may be released?

**Comment by bamx23** [comment]
Is there any progress?

**Comment by renep** [comment]
You can try the latest build from the develop branch that should fix issue:
see https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

**Comment by renep** [comment]
Ok I have done my investigation. This is not a bug, this is how it supposed to be. When you create an IPA for the AdHoc build, then you do not need the SwiftSupport folder in the IPA. This is fixed.

But: The IPA for submitting to the AppStore must contain the SwiftSupport folder with the swift libraries, that are already in Payload/Frameworks.
