### ISSUE TITLE
Entitlements processing problem

### ISSUE THREAD

**Issue by bamx23** [openbakery/gradle-xcodePlugin#286]
Hi there!

Here is a part of **archived-expanded-entitlements.xcent**:

```
    <key>com.apple.developer.associated-domains</key>
    <array>
        <string>applinks:some.link.com</string>
    </array>
```

But `codesign -d --entitlements - ./` returns:

```
    <key>com.apple.developer.associated-domains</key>
    <string>*</string>
```

I think you should use all archived-expanded-entitlements.xcent properties preferred to ones from embedded.mobileprovision.

**Comment by bamx23** [comment]
Will this problem be fixed soon?

**Comment by renep** [comment]
The *archived-expanded-entitlements.xcent* is ignored by the plugin and this is intentional.

Why?
There are two places to define the entitlements. One is in Xcode at the Capabilities tab and the second one is in apples developer portal. What if the settings in Xcode and Dev-Portal do not match? What is the proper entitlements then?
The correct answer (I think) is that the Dev-Portal must be right. Because the provisioning profile you get from the dev portal includes the entitlements, and this is take for codesigning.

The question now is: Have you add the associated domain settings in apples developer portal for you App?
If so, is the setting the the mobile provisioning profile?

**Comment by bamx23** [comment]
No, Xcode entitlements are preferred in signing. You can't add any "associated domain" into provisioning profile.

**Comment by renep** [comment]
[U+1F926](http://unicode.org/emoji/charts/emoji-released.html#1f926)

**Comment by renep** [comment]
see https://github.com/openbakery/gradle-xcodePlugin/issues/270#issuecomment-239087753

**Comment by bamx23** [comment]
Hi @renep!
Could you please add "Associated Domains" merging feature with the same logic as "Keychain Access Groups" merging.
The only way I could use "Associated Domains" with your plugin now is by providing custom entitlements file. But this workaround works only for single-bundle application(without any extensions). 
I don't know any other entitlements key that should work the same way like "Keychain Access Groups" or "Associated Domains" so this fix could be enough.

**Comment by renep** [comment]
The implementation I want to make here, is that all the values from the entitlements from the project is merged into the entitlements from the provisioning profile, if the settings does not exist.
If a value here should be modified, I don't think that the same behavior will work as with the "Key Access Groups"
I think I will add some hook later that values from the entitlement can be overridden. I'm not sure yet how this will look exactly, but I will do something flexible and hopefully simple ;-)

**Comment by bamx23** [comment]
Sounds good, I will look forward for it! (:

**Comment by renep** [comment]
I have implementing the merge of the settings from the *.xcent with the one from the provisioning profile.
If my continuous delivery pipeline fines do problems a development version should be deployed in the next 30 minutes (version 0.14.6.develop.90)

**Comment by bamx23** [comment]
I've tried `0.14.6.develop.90` and `0.14.6.develop.91`. `archived-expanded-entitlements.xcent` contains right value for `com.apple.developer.associated-domains`, but `codesign -d --entitlements - ./` shows, that resulting `com.apple.developer.associated-domains` is one from provisioning profile.
As I see in 03d68d0 log should contain `Found some entitlements settings in the archived entitlements...` line, but it doesn't.

**Comment by bamx23** [comment]
@renep should I provide more information? Additional logs or something

**Comment by renep** [comment]
I have seen that me continuous delivery pipeline has not succeed, so I don't know if a proper release was perform.
I was quite busy this week, so I had no time to investigate. I hope I find some time in the next few days ;-)

**Comment by renep** [comment]
There is a new test version more entitlement capabilities.

You have 3 options:
1. specify an entitlements file that is taken as it is. There is no modification, so this must have all the proper values:
```
xcodebuild {
  signing {
    entitlementsFile
  }
}
```

2. Specify nothing. Then the entitlements is extracted from the provisioning profile. If you have setup the capabilites in xcode properly then when creating an archive a *.xcent file is created with the settings from Xcode. If this file present then the entitlements that were extracted from the provisioning profile and the xcent are merged.

3. Specify the entitlements as parameter in signing: (as map)
```
xcodebuild {
  signing {
    entitlements = [
      'keychain-access-groups': [
        '$(AppIdentifierPrefix)com.example.App'
      ],
      'com.apple.developer.siri' = true
    ]	
  }
}
```
This works the same way as option 2, but instead of the xcent file the specified settings are used.

**Comment by renep** [comment]
I have run a test with using the xcent from the archive and it looks good with my example. Can you provide some additional information:
- What does the entitlements from your provisioning profile looks like: `security cms -D -i My.mobileprovision`
- What does the xcent look like
- What is the resulting entitlements: `codesign -d --entitlements :- Payload/My.app`

**Comment by bamx23** [comment]
`security cms -D -i My.mobileprovision` has returned an error:
```
security: SecPolicySetValue: One or more parameters passed to a function were not valid.
security: cert import failed: One or more parameters passed to a function were not valid.
security: problem decoding
```

But entitlements part of profile from `cat` is:
```xml
<key>Entitlements</key>
<dict>
    <key>keychain-access-groups</key>
    <array>
        <string><APP_PREFIX>.*</string>
    </array>
    <key>get-task-allow</key>
    <false/>
    <key>application-identifier</key>
    <string><APP_PREFIX>.<BUNDLE_ID></string>
    <key>com.apple.developer.associated-domains</key>
    <string>*</string>
    <key>com.apple.developer.team-identifier</key>
    <string><TEAM_ID></string>
    <key>aps-environment</key>
    <string>production</string>
</dict>
```

Content of `archived-expanded-entitlements.xcent` from the built app is:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>application-identifier</key>
    <string><APP_PREFIX>.<BUNDLE_ID></string>
    <key>aps-environment</key>
    <string>development</string>
    <key>com.apple.developer.associated-domains</key>
    <array>
        <string>applinks:<UNIVERSAL_LINK></string>
    </array>
</dict>
</plist>
```

Codesign has returned this:
```xml
Executable=<PATH_TO_BINARY>
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>application-identifier</key>
    <string><APP_PREFIX>.<BUNDLE_ID></string>
    <key>aps-environment</key>
    <string>production</string>
    <key>com.apple.developer.associated-domains</key>
    <string>*</string>
    <key>com.apple.developer.team-identifier</key>
    <string><TEAM_ID></string>
    <key>get-task-allow</key>
    <false/>
</dict>
</plist>
```

`<APP_PREFIX>, <BUNDLE_ID>, <TEAM_ID>, <UNIVERSAL_LINK> etc` are placeholders for the real values I can't publish here.

**Comment by bamx23** [comment]
Do you have an idea how to deal with this problem?

**Comment by renep** [comment]
I thought I have answered this but it looks like I have missed it 😳

The `My.mobileprovision` in the  `security cms -D -I My.mobileprovision` should be the provisioning profile you get from the apple developer member center. This should give a proper result, and no errors message.

**Comment by bamx23** [comment]
I've checked it again and now `security cms -D -I My.mobileprovision` works fine.
I think the problem is related to this line:
`[DEBUG] [org.apache.commons.configuration.DefaultFileSystem] Could not locate file archived-expanded-entitlements.xcent at <PATH_TO_APP>: no protocol: <PATH_TO_APP>`.

**Comment by renep** [comment]
Can you check if in the xcarchive that is created by the build a archived-expanded-entitlements.xcent is present? (or any *.xcent file)

**Comment by bamx23** [comment]
`build/archive/<APP_NAME>.xcarchive/Products/Applications/<APP_NAME>.app` does contain archived-expanded-entitlements.xcent which contains desired `com.apple.developer.associated-domains`.

**Comment by renep** [comment]
Ok, your archive has the xcent. So check the debug output when packaging. Here you should find `prepareEntitlementsForSigning` and can you post the debug log output that comes afterwards until a `performCodesign`.

**Comment by bamx23** [comment]
What version of plugin should I use?

**Comment by renep** [comment]
latest develop 0.15+
(I always use the the latest develop for all my builds, so this should be normally be very stable)

**Comment by bamx23** [comment]
Here it is: https://gist.github.com/bamx23/075ffd3117ea7cc75264294645ab4821

**Comment by renep** [comment]
Ok I see the problem.

As workaround: Can you try to delete the 'com.apple.developer.associated-domains' from the provisioning profile that you get from the the developer portal from apple. Than the value from the xcent should be merged into resuling entitlements.
I will try to address this problem soon, but I'm quite busy right now.

**Comment by bamx23** [comment]
Thank you!

**Comment by renep** [comment]
the fix from #359 can be testen with version lastest development build: `0.15.0.develop.107`

**Comment by bamx23** [comment]
Now it works as it should. Associated Domains merges and signature looks correct. Thank you!
Are you planning a release with this fix?

**Comment by bamx23** [comment]
Hi there! When are you planning to release 0.15.0?

**Comment by renep** [comment]
0.15.0 released
