### ISSUE TITLE
Make "derivedDataPath" optional

### ISSUE THREAD

**Issue by iThinker** [openbakery/gradle-xcodePlugin#291]
With "derivedDataPath" parameter, "scheme" is required. And if you pass "scheme", "target" and "configuration" are ignored. And you have no option of omitting "scheme", because this plugin uses "derivedDataPath".
It is a bit lame. I want not to use "scheme", but I am forced to do it, and create schemes for all combinations of target/configuration.

**Comment by renep** [comment]
You can try the latest develop version that should fix this issue:
`classpath "org.openbakery:xcode-plugin:0.14.2.develop.+"`

see also: https://github.com/openbakery/gradle-xcodePlugin#usage
