### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by Electryc** [openbakery/gradle-xcodePlugin#294]
Is there any active development towards supporting tvOS? 
If yes, on which branch ?

**Comment by renep** [comment]
I have not done much in the tvOS support yet. I have created an example so see what is working. The problem I found is that the tvOS simulator settings are not passed properly to the xcodebuild command. I think that a fix for this is a very simple one, but I don't know when I am able to implement it.
I'm currently on vacation therefor it will take some time until I can address this. But I will, and hopefully sooner than later ;-)
