### ISSUE TITLE
gradle package problem

### ISSUE THREAD

**Issue by renanstig** [openbakery/gradle-xcodePlugin#301]
Hello, 

It's my first time using gradle and I'm facing some problems that I can't understand what's happening.

I'm trying to generate an IPA file, so I set my build.gradle as you can see below:

plugins {
  id "org.openbakery.xcode-plugin" version "0.14.2"
}

xcodebuild {
  scheme = 'eDirectory11'
  target = 'eDirectory11'
  configuration = 'Release'
  type = 'iOS'
  simulator = 'false'
  signing {
      mobileProvisionURI = 'file://localhost/Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/distribution.mobileprovision'
      certificateURI = 'file://localhost/Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/gradlebuild.p12'
      certificatePassword = 'pwd'

  }
  infoPlist = 'eDirectory11-info.plist'

}

Then I run "gradle archive" , which works perfectly. As the ipa file is not generated, I'm trying to use "gradle package" and I got this error:

Execution failed for task ':package'.

> Command failed to run (exit code 139): '/usr/bin/codesign --force --sign iPhone Distribution: Arca Solutions (EMQXRSL6DK) --verbose /Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/build/package/Payload/eDirectory11.app/Frameworks/AFNetworking.framework --keychain /Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/build/codesign/gradle-1476127278278.keychain'
>   Tail of output:

I'm not sure what I'm doing  wrong and I hope you can help me with that.

Thanks in advance,
Renan.

**Comment by renep** [comment]
Hmm...
I don't see any obvious error in your configuration.
I'm wondering I there is any more output that would give a hint what the problem is.

Can you verify that the p12 contains a certificate that is for `iPhone Distribution: Arca Solutions (EMQXRSL6DK)`and that the Provisioning Profile also works with the project?
I would guess that here is somewhere the error.

**Comment by renanstig** [comment]
My p12 contains the correct certificate, I tried to run archive directly from xCode and it worked as expected after I deleted Derived Data folder. I tried to delete it before running gradle archive, but I still gt the same error.

**Comment by renep** [comment]
The gradle build does not use Xcode Derived Data folder. The gradle build puts everything into the build folder in you project. When deleting this folder, or running 'gradle clean' you get a fresh start.

About codesigning:
The codesign process when using the gradle build overrules all the settings in the Xcode project. Also it does __not__ use any certificate that is stored in the login.keychain, and also __not__ the mobile provisioning file stored in ` ~/Library/MobileDevice/Provisioning Profiles`
It only uses the things you have specified in your `build.gradle` file. And this things have to match.

For example the identity used for signing is read from the p12 certificate. So if your `distribution.mobileprovision` was not created using the certficate, then the codesigning will fail.

Can you try to manuelly run the failed codesign command that you have posted above, to see if there is some more output that indicates what the error is.

**Comment by renanstig** [comment]
My distribution.mobileprovision was created using the right certificate as it's the only one I have created in my account and xCode works fine with them when I set them manually and don't let xCode deal with certificates.

I ran the failed codesign command manually and I got this message:

-- Compiling
2016-10-11 11:37:23.727 xcodebuild[11613:412578]  DVTAssertions: Warning in /Library/Caches/com.apple.xbs/Sources/DVTFrameworks/DVTFrameworks-11224.1/DVTFoundation/Utilities/DVTFileSystemUtilities.mm:142
Details:  lstat('/Users/renan.camaforte/Library/Developer/Xcode/DerivedData/eDirectory11-axokzidllnvxaxczouywwkflhuek/Build/Products/Release-iphoneos/AFNetworking/AFNetworking.framework') failed with errno 2 (No such file or directory)
Function: DVTRecursiveMkdirResult dvt_recursiveMkdir_returningErrorString(NSString *__strong, NSString *__autoreleasing *)
Thread:   <NSThread: 0x7fb8b070b850>{number = 2, name = (null)}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.

Could it be a bug in xcode? 

Thanks,
Renan.

**Comment by renep** [comment]
have you executed this command?:
```
/usr/bin/codesign --force --sign iPhone Distribution: Arca Solutions (EMQXRSL6DK) --verbose /Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/build/package/Payload/eDirectory11.app/Frameworks/AFNetworking.framework --keychain /Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/build/codesign/gradle-1476127278278.keychain
```

**Comment by renanstig** [comment]
Sorry, I ran another command. When I ran the one you talked , I got this:

/Users/renan.camaforte/Desktop/iOS/edirectory11-ios2/build/package/Payload/eDirectory11.app/Frameworks/AFNetworking.framework: signed bundle with Mach-O universal (armv7 arm64) [org.cocoapods.AFNetworking]

FYI I'm using cocoapods to manage my dependencies.

**Comment by renanstig** [comment]
The build was successful after I specified the keychain:
`keychain="~/Library/Keychains/login.keychain"`, but I don't want to use it in that way. Any ideas?

Thanks,
Renan

**Comment by renep** [comment]
I would say that the certificate that you have exported into the p12 you have specified is not the correct one. If you specify the login.keychain, then the correct certificate is found, that matches with your provisioning profile and bundle identifier.

**Comment by Aswini999** [comment]
@renep , 

I've imported p12 certificate into login.keychain and provided keychain details in build.gradle as well. But 'package' is still failed.

```
ecadmins-Mac-mini:DemoApp macadmin$ gradle package/MyApp/Release
:provisioningClean
:provisioningInstall
:cocoapodsInstall
:xcodebuildConfig
:infoplistModify
:xcodebuild
Done
:archive
:keychainClean
:keychainCreate
:package FAILED
:keychainRemove

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package'.
> Command failed to run (exit code 1): '/usr/libexec/PlistBuddy -x /Users/myuser/<AppPath>/MyApp/build/tmp/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist -c Print Entitlements'
  Tail of output:
  Cannot parse a NULL or zero-length data
  Error Reading File: /Users/myuser/<AppPath>/MyApp/build/tmp/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist 

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 19.087 secs
```

Please guide me to fix this ASAP

Regards,
Aswini

**Comment by renep** [comment]
Looks like you provisioning file you have specifed is not correct, because it should contain entitlements, but it does not as it looks.

Why do you import the p12 into the login.keychain. The gradle plugins is designed to avoid the login.keychain completely. The plugin creates a new keychain that is uses and the in the build.gradle specifyied p12 is imported into this.
The reason the login.keychain is avoided is, that there are sometime other certificates that can can conflict with the certificate that should be uses.

**Comment by Aswini999** [comment]
@renep , 

I understand about login.keychain. I removed it.

And package is working fine, if I archive and export using xcode. When I select the profile then respective Certificate is displayed.

Also I tried to print plist using 'security cms -D -i' 
` security cms -D -i /Users/myuser/Downloads/inhouseprofile.mobileprovision >> test.plist`

Then tried 
`/usr/libexec/PlistBuddy -x test.plist -c 'Print Entitlements'`

Output: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>application-identifier</key>
	<string>B44H9X6N76.com.app.*</string>
	<key>com.apple.developer.team-identifier</key>
	<string>sampleid</string>
	<key>get-task-allow</key>
	<false/>
	<key>keychain-access-groups</key>
	<array>
		<string>sampleid.*</string>
	</array>
</dict>
</plist>
```

Please check if it is valid provisioning profile

Regards,
Aswini

**Comment by renep** [comment]
If the `/usr/libexec/PlistBuddy -x test.plist -c 'Print Entitlements'` command works it should be find. 
You have to make sure that the entitlements settings (Application Services at the App ID) at developer.apple.com / "Certificates, Identifiers & Profiles" portal match the capabilties that are needed for your app.
The settings that you have in Xcode under "Capabilities" are ignored by the plugin, because the settings at the developer.apple.com are the one that rules.

**Comment by Aswini999** [comment]
@renep 

Output when I execute gradle package task with --debug

```
17:00:33.275 [DEBUG] [org.openbakery.CommandRunner] Run command: 'security cms -D -i /Users/myuser/<AppPath>/MyApp/build/provision/gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.mobileprovision -o /Users/myuser/<AppPath>/MyApp/build/tmp/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist'
17:00:33.324 [INFO] [org.openbakery.CommandRunner] security: SecPolicySetValue: One or more parameters passed to a function were not valid.
17:00:33.331 [INFO] [org.openbakery.CommandRunner] security: cert import failed: write permissions error
17:00:33.331 [INFO] [org.openbakery.CommandRunner] security: problem decoding
17:00:33.333 [DEBUG] [org.openbakery.CommandRunner] Exit Code: 1
```

When I tried command with sudo, it worked.

Please check and suggest a fix.
