### ISSUE TITLE
Gradle stuck in "Waiting to acquire shared lock on daemon addresses registry"

### ISSUE THREAD

**Issue by renanstig** [openbakery/gradle-xcodePlugin#302]
Hello ,

I know it's not related to your lib, but I've been facing this issue for awhile and I'd like to know if you have any ideas to solve it. 

When I'm building my project, Gradle stucks in these three lines:

17:19:00.444 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
17:19:00.444 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired.
17:19:00.445 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.

Do you know what I can do to solve it?
Thanks,
Renan.

**Comment by renep** [comment]
Try to disable the gradle daemon:
https://docs.gradle.org/current/userguide/gradle_daemon.html

**Comment by renanstig** [comment]
I've disabled it and now it stucks in `XcodeBuildTask`. 

These are the last lines that are shown in terminal:

19:35:41.976 [INFO] [org.openbakery.CommandRunner] Build settings from command line:
19:35:41.976 [INFO] [org.openbakery.CommandRunner]     CODE_SIGN_IDENTITY = 
19:35:41.976 [INFO] [org.openbakery.CommandRunner]     CODE_SIGNING_REQUIRED = NO
19:35:41.977 [INFO] [org.openbakery.CommandRunner]     DSTROOT = /Users/administrator/build/eDir_iOS/com.arcasolutions.builder611938969-15610/code/build/dst
19:35:41.977 [INFO] [org.openbakery.CommandRunner]     OBJROOT = /Users/administrator/build/eDir_iOS/com.arcasolutions.builder611938969-15610/code/build/obj
19:35:41.977 [INFO] [org.openbakery.CommandRunner]     SHARED_PRECOMPS_DIR = /Users/administrator/build/eDir_iOS/com.arcasolutions.builder611938969-15610/code/build/shared
19:35:41.977 [INFO] [org.openbakery.CommandRunner]     SYMROOT = /Users/administrator/build/eDir_iOS/com.arcasolutions.builder611938969-15610/code/build/sym
19:35:41.977 [INFO] [org.openbakery.CommandRunner]

**Comment by renep** [comment]
Can you run the command with `-i` or `--debug` to see what `xcodebuild` does.

**Comment by laurre** [comment]
I had a similar problem because my Xcode scheme was not shared. This problem seems to be related to xcodebuild, not to this plugin. See here for more details: https://bitrise-io.github.io/devcenter/ios/known-xcode-issues/#issues-which-occur-with-the-xcode-command-line-tools-xcodebuild-but-not-with-xcodeapp

**Comment by renanstig** [comment]
Hi @laurre ,

You were right, this issue was occurring because my scheme wasn't shared!
Thanks for you reply!

Regards,
Renan.
