### ISSUE TITLE
Archive fails on 'xcodebuild clean -showBuildSettings' because of scheme name

### ISSUE THREAD

**Issue by bamx23** [openbakery/gradle-xcodePlugin#304]
With 0.14.3.develop.53 I have a problem with archive task:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean -showBuildSettings
xcodebuild: error: Unable to open workspace 'My.xcworkspace', and no scheme name was provided.
```

I think it's because my workspace has no scheme named after it. It could be solved by providing scheme and workspace to xcodebuild:

```
/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean -showBuildSettings -scheme MyScheme -workspace My.xcworkspace
```

**Comment by renep** [comment]
Can you test version `0.14.4.develop.54` if it works now.

**Comment by bamx23** [comment]
Now it works fine, thank you! Will wait for the next release.

**Comment by bamx23** [comment]
By the way, when do you plan to release 0.14.4?

**Comment by renep** [comment]
I can't say.
I have some things on my mind I want to add, and I don't know if this will be in 0.14.4 or the next release.
Also it looks like there are some issues I want to address in 0.14.4.

**Comment by renep** [comment]
As you see with #312 it is good not to release to soon ;-)

**Comment by bamx23** [comment]
I see, sure :)
