### ISSUE TITLE
Parameter 'projectFile' usage

### ISSUE THREAD

**Issue by christophherrmann** [openbakery/gradle-xcodePlugin#305]
Hi Rene,
I have a workspace with two .xcodeproj files. However if I try to set the parameter `projectFile` in the `xcodebuild` I still get an error message:

```
xcodebuild: error: The directory .... contains 2 projects, including multiple projects with the current extension (.xcodeproj). Specify the project to use with the -project option.
```

I tried setting the absolute path to the correct .xcodeproj as well as just the name. Nothing seems to work.

Thanks,
Christoph

**Comment by renep** [comment]
I have looked into the code, and the project file is not (yet) passed to the xcodebuild command. I think this is easy to fix and I will try to address this soon.

For now you can try to set the '-project' option using the additionalsParameters option, because these parameters are passed directly to the xcodebuild command.

**Comment by christophherrmann** [comment]
When I try to set the project file in the additionalParameters I get the following output:
`xcodebuild: error: You cannot specify both an Xcode project and a workspace`

The task looks something like this: 
```
xcodebuild {
  target 		= 'myTarget'
  scheme 		= 'myScheme'
  workspace = 'workspace.xcworkspace'
  additionalParameters = ["-project", "projectFile.xcodeproj"]
}
```

**Comment by renep** [comment]
Looks like that the `xcodebuild` command does not work when having a workspace and also two project files in the same directory.
Maybe moving one xcodeproj into a subdirectory will help.

**Comment by christophherrmann** [comment]
Yes, although I wanted to avoid this.
Thanks for your help!

**Comment by phatblat** [comment]
@christophherrmann I've added support for the `-project` parameter in #345. Would you be interested in testing that change with this issue?

**Comment by christophherrmann** [comment]
Hi, thanke but unfortunately I am not using gradle at the moment.
