### ISSUE TITLE
Could anyone help me investigate a issue which may be related to this gradle plugin?

### ISSUE THREAD

**Issue by youjenli** [openbakery/gradle-xcodePlugin#306]
Hi everyone

I am utilizing gradle with some ant task library and gradle xcode-plugin to build a cordova-like iOS project.
This iOS project was generated by a framework which called "MobileFirst" for enterprise app development.

We will invoke the ant task provided from MobileFirst to bundle web resource into native Android and iOS, then we use xcode plugin to build iOS project and archive executables to ipa file.
The iOS project has a cordova library project inside.

My problem is that the log message generated during build progress shows that one of a header file named **CDVViewController.h** in 
cordova library project just can't be found by xcodebuild, therefore it cannot build cordova library for our iOS app.  
However, gradle build process did not fail while xcodebuild suspend the build.
The log message of this build is right [here](https://github.com/openbakery/gradle-xcodePlugin/files/564056/terminal-output-20161101.txt).

I've check ios project settings to find out whether the project file registry has drop this header unexpectedly. 
But it seems that Xcode is able to located it properly.

Since we use web technologies to implement mobile app, we are not pretty familiar with native iOS app development. 
Could anyone help us find out what's wrong in this iOS project?

Any suggestion will be appreciated.
Please contact me privately If you want to request for some more code or files.

**Comment by renep** [comment]
If you check the log file:
```
/Users/experiment/git/synnexappmobile/SynnexAPP/apps/Synnex/iphone/native/Frameworks/IBMMobileFirstPlatformFoundationHybrid.framework/Headers/MFPMainViewController.h:35:9: fatal error: 'Cordova/CDVViewController.h' file not found
#import <Cordova/CDVViewController.h>
        ^
1 error generated.
```
