### ISSUE TITLE
It's trying to code-sign a nonexistent framework

### ISSUE THREAD

**Issue by cburtbrown** [openbakery/gradle-xcodePlugin#307]
The :package stage of my build is failing. I was concerned that my keychain isn't set up right so I'm just using login.keychain. I get the following error.

    :package FAILED
    :keychainRemove

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':package'.
    > Command failed to run (exit code 1): '/usr/bin/codesign --force --sign B4408AF2A45118B355B58A5FC322EDAB2EDCB3E6 --verbose ../project/build/package/Payload/Game.app/Frameworks/UnityAds.framework --keychain /Users/_____/Library/Keychains/login.keychain'
      Tail of output:

    (...lots of dylibs codesigned correctly...)

      .../project/build/package/Payload/Game.app/Frameworks/UnityAds.framework: No such file or directory

The UnityAds.framework file does exist, but it's a broken symlink. It links relative to

    UnityAds.framework -> ../Fyber_UnityAds_2.0.5-r1.framework/Resources/UnityAds.Frameworks

None of that exists, there is no Fyber_UnityAds_2.0.5-r1.framework inside Game.app.

I don't at all understand what the plugin is trying to do here. I do have a cocoapods dependency upon FyberMediationUnityAds (~> 2.0) among many others. There are no .frameworks at all inside Game.app/Frameworks. Why would you have a .framework file inside a .app file?

My build.gradle file looks like this:

    plugins {
        id 'org.openbakery.xcode-plugin' version '0.14.3'
    }

    xcodebuild {
        workspace = 'Game.xcworkspace'
        target = 'Game'
        scheme = 'Game'
        simulator = false

        signing {
            identity = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
            mobileProvisionURI = new File('dev.mobileprovision').toURI()
            keychain="~/Library/Keychains/login.keychain"
        }
    }

**Comment by renep** [comment]
You say that the UnityAds.framework exits but is a broken symlink. 
Have you tried to delete the broken symlink?

**Comment by cburtbrown** [comment]
It seems to get regenerated on the `package` step.

I'm starting to suspect that this is a problem specific to FyberMediationUnityAds. I was able to reproduce this with a test project that only depends on that one pod, and it goes away if I switch it out for others.

That framework file is there in my non-gradle build too, I guess it just doesn't do anything.

**Comment by renep** [comment]
The plugin works as follows:
1. Build - compile with xcodebuild and the result is in `build\sym\<config>-iphoneos\<name>.app
2. Archive - take the stuff from build\sym and create an xcarchive in `build\archive` 
3. Package - take archive and create and IPA. Codesign happens here.

You could check where the on which places the framework exits:
e.g. `find build -name "Fyber*.framework"`

**Comment by cburtbrown** [comment]
So yes, it's the build step which produces a .framework symlink -- it's actually called UnityAds.framework -- inside the Project.app/Frameworks folder.

I'm really not sure if it's supposed to do that.

**Comment by renep** [comment]
Maybe check out build settings in Xcode. Maybe you have some script execution or something that should not be done.

**Comment by cburtbrown** [comment]
But it happens on a blank project with just

	source 'https://github.com/cocoapods/Specs.git'

	platform :ios, '7.0'

	target 'TestProject' do

	  pod 'FyberMediationUnityAds'

	end

And no custom build settings at all.

**Comment by YogeshBharate** [comment]
I am facing same error but for Alamofire.framework, how should solve this ?

**Comment by renep** [comment]
Can you create a example project with the Alamofire.framework where you can reproduce this issued and send me this project.
