### ISSUE TITLE
/usr/local/bin/pod No such file or directory

### ISSUE THREAD

**Issue by cburtbrown** [openbakery/gradle-xcodePlugin#308]
On one of my machines (I have no idea what's different between the two) the logic in AbstractCocoapodsTask.groovy isn't working to derive the correct path for CocoaPods:

    ba-mac2:Game build$ which pod
    /Users/build/.rvm/gems/ruby-2.3.0/bin/pod

    ba-mac2:Game build$ gradle xcodebuild
    :cocoapodsInstall
    Run pod setup
    :cocoapodsInstall FAILED

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':cocoapodsInstall'.
    > java.io.IOException: Cannot run program "/usr/local/bin/pod" (in directory "."): error=2, No such file or directory

    * Try:
    Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

    BUILD FAILED

    Total time: 1.51 secs

    ba-mac2:Game build$

**Comment by renep** [comment]
Bug...

As workaround you can install cocoapods for all uses  `sudo gem install cocoapods` or remove the `Users/build/.rvm/gems/ruby-2.3.0/bin/pod` from your PATH, do that `which pod` does not return anything.

**Comment by renep** [comment]
see https://github.com/openbakery/gradle-xcodePlugin/commit/ae4cab0ab6411f28e0d5d7a28ceadabe302687b8

(forgot to add issue number in the comment)
