### ISSUE TITLE
onDemandResources folder missing in archive

### ISSUE THREAD

**Issue by anandfnc** [openbakery/gradle-xcodePlugin#309]
I am using latest plugin xcode-plugin:0.14.+ and building archive using "cradle archive". Able to generate archive but onDemandResources folder is missing in it. Do anyone face this issue?

**Comment by renep** [comment]
Looks like you are the first to use onDemandResources with the plugin ;-)

If you could provide an example project, or modify one example in the project and send a pull request, it would speed up things to support this.

**Comment by anandfnc** [comment]
Thanks for prompt reply. Before modifying some example project, let me tell how to enable onDemandResources in Xcode project.

In Xcodeproject build settings, Set the following under "Assets" section.
1. Enable on Demand Resources : yes
2. On Demand Resources Initial Install Tags : SampleScreens

Again ,in project settings under "Resources Tags" 
Add "SampleScreens" under "Initial Install tags". Then, add some image files in .xcassets and tag them as "SampleScreens" under "On Demand Resources Tag" in images attribute inspector.

Thats it. 
When i create the archive using xcodebuild in terminal command line , i can see the OnDemandResources folder inside .archive/Products/ .
But when i archive using "gradle archive", i don't see that folder in .archive. But i can see that folder in "build/sym/Development-iphoneos/" along with .app and .dSYM files.

Please let me know if this helps.

**Comment by renep** [comment]
`<Config>-iphoneos/OnDemandResources` needs to be copied to `*.xcarchive\Products\

**Comment by anandfnc** [comment]
I tried this again now with 0.14.4.develop.70..but still "OnDemandResources" folder is not copied into "archive/sample.xcarchive/Products"...

**Comment by renep** [comment]
I have only updated the example and investigated what to do ;-)

**Comment by renep** [comment]
see also`xcodebuild -h` for all available export options.

**Comment by anandfnc** [comment]
ok ..:-)

**Comment by renep** [comment]
@anandfnc can you test the latest develop version if this works now?

**Comment by anandfnc** [comment]
@renep Sure.will test and let you know..Thanks

**Comment by renep** [comment]
I'll close this issue, because I have not got any feedback that this is not working. 
If this is not fixed, then reopen the issue.
