### ISSUE TITLE
Using useXcodebuildArchive when creating an archive does not create anything

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#311]
The build/archive/...xcarchive is empty

My guess is that it has something to do with codesigning. Therefor not easy to fix as it looks like.

**Comment by bamx23** [comment]
In my case application archive was in `build/dst/Applications/`.

**Comment by renep** [comment]
You have an folder with the xcarchive extension?

**Comment by bamx23** [comment]
`build/dst/Applications/` contains just `MyApp.app` file.
With this flag build fails and here a structure of `build` directory:
```
build/
    archive/
        MyApp.xcarchive/
            *empty*
    codesign/
        gradle-***.keychain
        my-cert.p12
    derivedData/
        Info.plist
        Logs/
            ...
        ModuleCache/
            ...
    dst/
        Applications/
            MyApp.app
                *app stuff*
    obj/
        *targets and its objects*
    package/
        Payload/
            *empty*
    project.plist
    provision/
        my.mobileprovision
    sym/
        Release-iphoneos/
            *some stuff*
            MyApp.app/
                *same app stuff*
            MyApp.app.dSYM/
                *correct symbols*
    xcodebuild-archive-output.txt
    xcodebuild-output.txt
```
I hope it'll help you.

**Comment by bamx23** [comment]
Here is an interesting case. My steps:

1. Remove `build` directory (clean)
2. Run archive and package first time
3. Fail on package because of empty xcarchive
4. Run the same tasks again
5. Fail on archive with linking error (Xcode can't find bitcode for armv7, arm64 `ld`s fine step before)

**Comment by bamx23** [comment]
Do you have any idea what to do with this issue? Dose this functionality works on your side?

**Comment by renep** [comment]
Nope it does not work on my side. That is why I created this issue.
I have not found out why it does not work.
I have a feeling that codesigning here is the problem. If so, than this is not an easy one to fix.

**Comment by bamx23** [comment]
If you produce archive without signing like this:
```bash
xcodebuild -workspace "My.xcworkspace" -scheme "MyScheme" -configuration "Release" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -archivePath "myarchive" clean archive
```
it will be placed in `myarchive.xcarchive`.
But there will be no signing entitlements. So you still should create it by merging one from provisioning profile with one from application settings.
