### ISSUE TITLE
Archive fails on 'xcodebuild clean -showBuildSettings' because of working directory

### ISSUE THREAD

**Issue by paleozogt** [openbakery/gradle-xcodePlugin#312]
With 0.14.4.develop.65 I'm having a problem with the archive task:

```
Execution failed for task ':app:archive'.
> Command failed to run (exit code 66): '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean -showBuildSettings'
  Tail of output:
  xcodebuild: error: The directory /Users/paleozogt/Development/MyProj does not contain an Xcode project or workspace.
```

I think it's because my build.gradle is in a sub-project (`MyProj/app`).  The other tasks behave properly, but it seems like archive depends on what directory the `./gradlew` invocation is run from.

**Comment by renep** [comment]
Does this only happen with one of the latest development version or also with the latest official 0.14.3?

**Comment by renep** [comment]
Does you project have a workspace?
If so, then you need to specify the 'scheme'  with
```
xcodebuild {
  scheme = 'MyScheme...`
...
}
```

The workspace is automatically found if only one is present.

**Comment by paleozogt** [comment]
It's also happening with the latest release `0.14.3`.

The project doesn't have a workspace.  I'll try setting the scheme anyway and see what happens...

**Comment by paleozogt** [comment]
Setting the `scheme` didn't change the error fyi.

**Comment by paleozogt** [comment]
I also made a workspace with the same name as the project and tried it with `scheme` set.  Same error.

**Comment by renep** [comment]
Is the build.gradle file in the same directory as the .xcodeproj File?

**Comment by paleozogt** [comment]
Yes.  The project is like this:
```
build.gradle                     // top-level gradle
gradle.properties
gradlew
gradlew.bat
subproj1/
    build.gradle
    ....
subproj2/
    build.gradle
    ...
app/
    build.gradle                 // gradle file with xcode-plugin
    MyProj/
    MyProj.xcodeproj
```

and I run the build like this:
```
./gradlew app:build app:archive app:package
```

**Comment by paleozogt** [comment]
If I run it the build like this:
```
cd app
../gradlew build archive package
```
it will work.  This makes me think that the command executor is accidentally using the current working directory rather than the projectDir.

**Comment by renep** [comment]
I think the problem is the location of the .xcodeproj file, because the plugins needs to find this to get some build settings and it looks in the current directory, not in the directory where the build should be executed.

**Comment by paleozogt** [comment]
What's odd is that `build` and `package` will work, so it seems like they're finding the xcodeproj file properly.  It's just the `archive` package when it tries to clean.

**Comment by renep** [comment]
Can you run with the `--debug` option, then you an see the `xcodebuild` command with all the parameters. That should give a clou.

**Comment by paleozogt** [comment]
I have run it with `--debug`-- the relevant output is in my first comment, repeated here:
```Execution failed for task ':app:archive'.
> Command failed to run (exit code 66): '/Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild clean -showBuildSettings'
  Tail of output:
  xcodebuild: error: The directory /Users/paleozogt/Development/MyProj does not contain an Xcode project or workspace.```

**Comment by renep** [comment]
Ok I think I know now whats wrong.

**Comment by renep** [comment]
Can you try the latest develop build if this fixes this issue.
see https://github.com/openbakery/gradle-xcodePlugin#current-develop-version

**Comment by paleozogt** [comment]
Sure.  Has it been deployed?  I'm still getting `0.14.4.develop.65` which is the version I originally tested on.

**Comment by renep** [comment]
should be `0.14.4.develop.68`
try to run with `--refresh-dependencies`

**Comment by paleozogt** [comment]
`0.14.4.develop.68` fixes it!  :)
