### ISSUE TITLE
All plist files are converted to binary when archiving

### ISSUE THREAD

**Issue by fdubuisson** [openbakery/gradle-xcodePlugin#313]
The 'archive' task takes all '.plist' files in the application bundle and converts to binary. Whilst this is understable for the Info.plist, the others (application specific ones) should remain unaffected.

**Comment by renep** [comment]
Can you enlighten my why this is unstable?

**Comment by fdubuisson** [comment]
Just that we have some plist files (application properties) in our bundles that are read by a library supporting text-only plist files.
Imho, a more common rule would be that the build process should not affect files that are not involved in this process itself.

**Comment by renep** [comment]
I don't know if it makes sense to add an options to the archive task to avoid converting plist files to binary.

There is stuff to add to the plugin that has more priority to me, that this issue.

As a solution you can use add a custom task to you build.gradle file that converts the binary plist back to xml before you create the ipa. With the power of gradle should not be a difficult task to execute `plutil -convert xml1 Info.plist` for the plists in question.

**Comment by fdubuisson** [comment]
Imho, this should not be an option. I don't see why the default behavior would be to convert all plist files; when building with XCode, only the application plist is converted. Others are left untouched.

But I agree that this is not a critical issue; we can deal with it (in our case, just changing the files extension).
