### ISSUE TITLE
create IPA from archive using -exportOptionsPlist

### ISSUE THREAD

**Issue by anandfnc** [openbakery/gradle-xcodePlugin#315]
I am trying to build IPA from archive using exportOptionsPlist with OnDemandResources and AppThining options. Can you please let me know how to do this in gradle. I am not able to configure the task for the same.
Please find the xcodebuild command used in script as of now below.

`xcodebuild -verbose -exportArchive -archivePath sample.xcarchive -exportPath sample.ipa -exportOptionsPlist sample.plist`

sample.plist:

```
<dict>
	<key>method</key>
	<string>enterprise</string>
	<key>embedOnDemandResourcesAssetPacksInBundle</key>
	<true/>
	<key>thinning</key>
	<string>&lt;thin-for-all-variants&gt;</string>
	<key>compileBitcode</key>
	<false/>
	<key>teamID</key>
	<string>***********</string>
</dict>
```

**Comment by renep** [comment]
I think I will add the options to the build.gradle file like: 

```
package {
  embedOnDemandResourcesAssetPacksInBundle = true
  compileBitcode = true
  teamID = "****"
 ...
}
```

what do you think?

**Comment by anandfnc** [comment]
Yes..we can try like this...There are more options available for exportOptionsPlist..will you able to incorporate most of them? For AppStore, i use following options as well..

```
	<key>method</key>
	<string>app-store</string>
	<key>uploadBitcode</key>
	<true/>
	<key>uploadSymbols</key>
	<true/>

```

**Comment by renep** [comment]
I know that there are more options, I hope that all are listed when executing `xcodebuild -h` ;-)
