### ISSUE TITLE
Keychain troubles is macOS Sierra?

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#316]
I have read this stackoverflow posting and I'm wondering if this is also a issue with the gradle-xcodePlugin: http://stackoverflow.com/questions/39868578/security-codesign-in-sierra-keychain-ignores-access-control-settings-and-ui-p

I have not updated my CI Box not yet to macOS Sierra (but will soon)
So if anybody has this issue let me know.

I post this as issue, because I do to search a lot if this issue occurs.

**Comment by phil443** [comment]
Our CI server has been updated to Sierra recently and we're now getting this error when the Gradle Xcode plugin runs the codesign command:

"SecKey API returned: -25308"

I've been unable to resolve this so have to build manually from Xcode for now.

I assume this is related to the stackoverflow issue linked above. This issue contains the following accepted answer which might be useful: http://stackoverflow.com/a/40039594

**Comment by renep** [comment]
I cannot reproduct the `SecKey API returned: -25308` with my environment. I have updated one build node to Sierra and I have run the build there and I cannot reproduce this issue.

Nevertheless I will try to add the additional command when creating the keychain, so see if it solve your issue. I hope I will find time for this soon ;-)

**Comment by phil443** [comment]
Thanks for that, I forgot to mention we use Jenkins for our CI environment. I'll keep digging in case it is an issue specific to our environment.

**Comment by phil443** [comment]
I just found this as well which describes the same environment as ours (OSX slave accessed via ssh from Jenkins) and the same error when code signing:

https://sinofool.net/blog/archives/322

This suggests a similar command to the stackoverflow post, which should be used after the keychain is created, and before it is used.

"security set-key-partition-list -S apple: -k <Password> -D <Identity> -t private"

**Comment by renep** [comment]
I have tested now to build when connected via ssh, but also I cannot reproduce this problem.

As I said before, I will add this security line to see if this fixes your problem.

**Comment by renep** [comment]
Can you please test the 0.14.5.develop version.
see https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

**Comment by phil443** [comment]
Hi, I'm getting the following error now with the 0.14.5.develop version:

`Command failed to run (exit code 1): 'security set-key-partition-list -S apple: -k -D -t private'`

It looks like the command is missing the password and identity values for the -k and -D options respectively. Apparently these were also missing in my previous post which I've edited now.

**Comment by huangjimmy** [comment]
Me too with org.openbakery:xcode-plugin:0.14.5.develop.+

:keychainCreate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keychainCreate'.
> Command failed to run (exit code 1): 'security set-key-partition-list -S apple: -k -D -t private'
  Tail of output:
      0x00000007 <blob>=<NULL>
      0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
      0x00000009 <uint32>=0x00000049  "\000\000\000I"
      0x0000000A <uint32>=0x00000100
      0x0000000B <uint32>=0x00000100
      0x0000000C <blob>=0x0000000000000000
      0x0000000D <blob>=0x0000000000000000
      0x0000000E <uint32>=0x00000000
      0x0000000F <uint32>=0x00000000
      0x00000010 <uint32>=0x00000001
      0x00000011 <uint32>=0x00000000
      0x00000012 <uint32>=0x00000000
      0x00000013 <uint32>=0x00000001
      0x00000014 <uint32>=0x00000001
      0x00000015 <uint32>=0x00000001
      0x00000016 <uint32>=0x00000000
      0x00000017 <uint32>=0x00000000
      0x00000018 <uint32>=0x00000000
      0x00000019 <uint32>=0x00000000
      0x0000001A <uint32>=0x00000001

* Try:


Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by huangjimmy** [comment]
I modify my build.gradle file by replacing  classpath "org.openbakery:xcode-plugin:0.14.+" with 	    classpath "org.openbakery:xcode-plugin:0.14.4"

Now I can build my iOS project successfully.

The reason why it fail is that you added a new command "security set-key-partition-list -S apple: -k  -D -t private" in 0.14.5 and this command failed.

The error message of the failure is "security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct."

It seems that you added this command in order to solve some problem, but this command actually causes problem in my Mac.

**Comment by renep** [comment]
Lastest develop build 83 should fix this issue now.
