### ISSUE TITLE
Build fails on archive reading Info.plist

### ISSUE THREAD

**Issue by bamx23** [openbakery/gradle-xcodePlugin#318]
Hi there! I've found a problem. If build settings have a target+configuration that does not have ProductBundleID and Info.plist path build will fail.

Problem is here: https://github.com/openbakery/gradle-xcodePlugin/blob/a7bde436a955b20c102527d86bbca98ef01a5b8b/plugin/src/main/groovy/org/openbakery/XcodeBuildPluginExtension.groovy#L408

Build fails this way:

    [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException: Cannot get property 'absolutePath' on null object
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.util.PlistHelper.getValueFromPlist(PlistHelper.groovy:36)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.util.PlistHelper$getValueFromPlist$1.call(Unknown Source)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.XcodeBuildPluginExtension$_getBuildConfiguration_closure7.doCall(XcodeBuildPluginExtension.groovy:408)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.XcodeBuildPluginExtension.getBuildConfiguration(XcodeBuildPluginExtension.groovy:402)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.XcodeBuildPluginExtension$getBuildConfiguration$3.call(Unknown Source)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.XcodeBuildArchiveTask.createEntitlements(XcodeBuildArchiveTask.groovy:272)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.XcodeBuildArchiveTask$createEntitlements$0.callCurrent(Unknown Source)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.openbakery.XcodeBuildArchiveTask.archive(XcodeBuildArchiveTask.groovy:364)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    [ERROR] [org.gradle.BuildExceptionReporter]  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    [ERROR] [org.gradle.BuildExceptionReporter]  ... 60 more

Plugin version `0.14.4.develop.69`

**Comment by renep** [comment]
should be fixed in version `0.14.4.develop.70`

**Comment by bamx23** [comment]
Does `0.14.4.develop.71` ok? Or should I choose 70?

**Comment by renep** [comment]
Don't know if 71 works for you or if you have this issue #317

**Comment by bamx23** [comment]
By the way `0.14.4.develop.70` haven't fixed this problem. I see the problem in the latest `develop` code I mentioned above (`XcodeBuildPluginExtension.groovy#L408`)

**Comment by renep** [comment]
Can you test version `0.14.4.develop.72`

**Comment by bamx23** [comment]
Now it fails with this:
```
[Gradle failure report] Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/impldep/org/apache/commons/lang/StringUtils
[Gradle failure report]   at org.openbakery.codesign.ProvisioningProfileReader.extractEntitlements(ProvisioningProfileReader.groovy:207)
[Gradle failure report]   at org.openbakery.codesign.ProvisioningProfileReader$extractEntitlements$4.call(Unknown Source)
[Gradle failure report]   at org.openbakery.codesign.Codesign.createEntitlementsFile(Codesign.groovy:143)
[Gradle failure report]   at org.openbakery.codesign.Codesign$createEntitlementsFile$0.callCurrent(Unknown Source)
[Gradle failure report]   at org.openbakery.codesign.Codesign.sign(Codesign.groovy:51)
[Gradle failure report]   at org.openbakery.codesign.Codesign$sign.call(Unknown Source)
[Gradle failure report]   at org.openbakery.packaging.PackageTask.packageApplication(PackageTask.groovy:101)
[Gradle failure report]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
[Gradle failure report]   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
[Gradle failure report]   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
[Gradle failure report]   at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
[Gradle failure report]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
[Gradle failure report]   at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
[Gradle failure report]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
[Gradle failure report]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
```

**Comment by renep** [comment]
already fixed. build is running...

**Comment by bamx23** [comment]
`0.14.4.develop.72` works, thank you
