### ISSUE TITLE
Failed to apply plugin [id 'org.openbakery.xcode-plugin']: Could not generate a proxy class for class org.openbakery.packaging.PackageTask.

### ISSUE THREAD

**Issue by la-urre** [openbakery/gradle-xcodePlugin#319]
I am having problems when trying to use this tool on my project. I get the following error:

> Failed to apply plugin [id 'org.openbakery.xcode-plugin']
> Could not generate a proxy class for class org.openbakery.packaging.PackageTask.

After having activated the stacktrace, I can see this more helpful message: 

> Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/logging/text/StyledTextOutput

I am using Gradle 2.12, and maybe this is a too old version. I can upgrade my install, so this should fix the problem, but I don't know if there is something that could be done to improve the tool. As a side note, this StyledTextOutput class is in an internal package, so I guess it is not recommended to use it.

**Comment by renep** [comment]
You need gradle version 2.14 or higher.

**Comment by viktorgardart** [comment]
Got the exact same issue, gradle version 2.14.1.

**Comment by renep** [comment]
With gradle 2.14 the `StyledTextOutput` class was move to an internal package, but the plugins uses this class. There was no replacement yet.

The lastest gradle version is 3.4.1, so can you try that.

**Comment by viktorgardart** [comment]
@renep Same issue with 3.4.1 😕

**Comment by renep** [comment]
what plugin version do you use?

**Comment by viktorgardart** [comment]
`classpath "org.openbakery:xcode-plugin:0.14.+"`

**Comment by renep** [comment]
can you run:
```
gradle tasks --refresh-dependencies
```

to see what is downloaded

**Comment by viktorgardart** [comment]
```
☁  iOS [develop] ⚡ gradle tasks --refresh-dependencies
Download http://repository.openbakery.org/org/openbakery/xcode-plugin/0.14.6.develop.98/xcode-plugin-0.14.6.develop.98.pom
```

**Comment by renep** [comment]
and `gradle -version` says 2.14 or higher?

e.g.
```
#gradle -version

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------
```

**Comment by viktorgardart** [comment]
yeap!

```
------------------------------------------------------------
Gradle 3.4.1
------------------------------------------------------------
```

**Comment by renep** [comment]
very odd...
can you try to clean the gradle cache:
```rm -rf ~/.gradle/caches```

On my box I also have gradle version 2.14.1 and use the same xcode-plugin-0.14.6.develop.98 as you do, and I have no problems.

**Comment by viktorgardart** [comment]
Didn't help :/ 

Will have to look at this tomorrow. Will keep this updated 👍

**Comment by renep** [comment]
Do you use sdkman?

I was able to reproduce this issue on a box where sdkman was installed and grade was installed using sdkman.
When using the gradle wrapper I saw that also the gradle jars from the sdkman were included and here it looks a wrong jar was included.

Solution: `rm -rf ~/.sdkman` 😛

**Comment by viktorgardart** [comment]
I don't :/ 
Ended up building it with Fastlane instead 👍
