### ISSUE TITLE
Documentation: 'If the scheme is set the configuration and target is ignored' is wrong

### ISSUE THREAD

**Issue by laurre** [openbakery/gradle-xcodePlugin#320]
I found this sentence in the documentation, in the Parameters.md file, in the *scheme*  parameter section:

> If the scheme is set the configuration and target is ignored

I tried to remove the target parameter to have only a scheme parameter, like this: 

```
xcodebuild {
  scheme = 'MyScheme'
}
```

But I get an error saying: "Execution failed for task 'xcodebuildConfig': xcodebuild.target is null".

Is it a mistake in the documentation ?

**Comment by renep** [comment]
Yes this is a mistake in the documentation. 
At least for now, because when using a scheme, the target could be parsed from the scheme, but that is not yet the cause.

**Comment by renep** [comment]
Updated see: https://openbakery.org/gxp/parameters/xcodebuild.html
