### ISSUE TITLE
Add a quiet option to (partially?) hide logs generated by xcodebuild

### ISSUE THREAD

**Issue by la-urre** [openbakery/gradle-xcodePlugin#322]
A lot of logs are displayed in the console, and I was wondering if it was possible to deactivate them through an option, like quiet.

**Comment by renep** [comment]
I'm a bit puzzeled, because the gradle xcode plugin does hide all the logs from xcodebuild per default.
Only Warnings and Error are printed!

If you want to see the full log you must add the `-i` or `--debug` option, otherwise you don't see much.

**Comment by laurre** [comment]
You are right, the logs I see are the warnings of my project. And what if I want to deactivate them anyway (I can't fix them all right now) ?

**Comment by renep** [comment]
Got to you xcode project and fix the warnings.
Warnings are there for a reason ;-)

**Comment by laurre** [comment]
I know I should definitely fix the warnings and that this is the ideal solution. My problem is that my unit tests are generated by a tool, so I can't fix the tests right away, there is simply too much to do. Anyway I think the log level should be configurable. I would like to help, but I don't know the inners of gradle plugins enough.
