### ISSUE TITLE
Test reports generation ?

### ISSUE THREAD

**Issue by la-urre** [openbakery/gradle-xcodePlugin#324]
I would like to know if this plugin generates reports for the unit tests ? If not then how I could I implement this mechanism ?

**Comment by renep** [comment]
Yes in does in the junit xml format.
You find the report in the `build/test` directory after you execute `gradle test `
Your project needs to have unit tests of course ;-)

**Comment by laurre** [comment]
I think this should be documented somewhere. I can do it if you tell me where to write it !

**Comment by renep** [comment]
I have started to create a better documentation here: https://openbakery.org/gxp/
But the source for this site is not hosted on github yet. I will try to move this to this project.

**Comment by renep** [comment]
I have put the source for the documentation now into an own project that is hosted on https://openbakery.org/gxp/:
https://github.com/openbakery/gradle-xcodePlugin-Documentation
