### ISSUE TITLE
Gradle warning: Cannot assign 'String' to 'Class<Platform>'

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#325]
I'm using version `0.14.4` of the Gradle Xcode plugin with version `3.2.1` of Gradle and I'm getting a warning for the `platform` assignment as follows:

    Cannot assign 'String' to 'Class<Platform>'

Should I be worried? Am I doing something wrong? This is what my `bulid.gradle` file looks like (with all the unrelated bits stripped off):

    plugins {
        id 'org.openbakery.xcode-plugin' version '0.14.4'
    }

    xcodebuild {
        destination {
            platform = 'iOS Simulator'
            name = 'iPhone 6'
            os = '9.3'
        }
    }

**Comment by renep** [comment]
Strange. I need to test this.

I use the simple syntax for specifying simulators that looks like this:

```
xcodebuild {
    destination  = [ 'iPhone 6' ]
}
```

or 

```
xcodebuild {
    destination  = [ 'iPhone 6',  'iPad Air', 'iPhone 7' ] // for multiple
}
```

**Comment by adil-hussain-84** [comment]
Is it possible to use the simple syntax to specify both name and os? Something like `iPhone (9.3)` perhaps?

**Comment by renep** [comment]
No, the most recent simulator is used. So If you have iOS 10 simulators and also iOS 9 simulators installed, then the iOS 10 simulators are used.

**Comment by adil-hussain-84** [comment]
Just looked into it a bit more and looks like your plugin is okay. For some reason my IDE (IntelliJ IDEA Ultimate 2016.3) is resolving the `platform` attribute in my `build.gradle` file to be an object of type `org.gradle.platform.base.Platform` rather than a simple `String`. The build does actually run fine. This is a compiler warning.
