### ISSUE TITLE
Gradle build error: No matching simulators found

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#326]
I just tried bumping up the Gradle Xcode plugin from version `0.14.2` to `0.14.4` in my project with no other changes in my `bulid.gradle` file and I'm getting the following Gradle build error:

    No matching simulators found!

This is what my `bulid.gradle` file looks like (with all the unrelated bits stripped off):

    plugins {
        id 'org.openbakery.xcode-plugin' version '0.14.4'
    }

    xcodebuild {
        destination {
            platform = 'iOS Simulator'
            name = 'iPhone 6'
            os = '9.3'
        }
    }

If I drop the Gradle Xcode plugin back down to `0.14.2` the Gradle build works. If I keep the Gradle Xcode plugin version to `0.14.4` and specify the `os` as `10.1` the Gradle build works.

(Unfortunately I cannot keep the `os` to `10.1` in my `build.gradle` file because I have unit tests in my project that fail because of an Xcode issue with the latest iOS release.)

**Comment by renep** [comment]
Do you use the new Xcode 8.2?

**Comment by adil-hussain-84** [comment]
Downloading Xcode 8.2 now. Will try this again later today.

**Comment by adil-hussain-84** [comment]
Unfortunately this is still failing with Xcode 8.2. The Gradle build fails with `No matching simulators found` error message when I set `os = '9.3'` (and the build fails also for `os` level lower than `9.3`). This is the info message I see in the output:

    No matching simulators found for specified destinations: [Destination{platform='iOS Simulator', name='iPhone 6', arch='null', id='null', os='9.3'}]

In the list of available simulators on my machine I see this:

    -- iOS 9.3 --
        ...
        iPhone 6 (DCF7E667-92F9-4E41-A330-E94B747851B2) (Shutdown)
        ....

**Comment by renep** [comment]
Have you try to run `gradle simList` to see the available simulators.
Xcode 8.2 includes only iOS Simulator for iOS Version 10.2. Do you really want to use iOS 9.3, and have you installed the additional SDK?

**Comment by Doxxer** [comment]
Have the same error: XCode 8.2, trying iPhone 6 (9.3) simulator.

`gradle simList` contains this simulator:
```
-- iOS Simulator 9.3 --
...
         iPhone 6 (2021C13F-9809-4438-98E2-A99603909CD2)
...
```

It works with XCode with iPhone 6 (9.3) simulator

**Comment by Doxxer** [comment]
@renep what is the reason of [2nd parameter in this function](https://github.com/openbakery/gradle-xcodePlugin/blob/master/libxcode/src/main/groovy/org/openbakery/xcode/DestinationResolver.groovy#L24)?

I think, there should be just `return simulatorControl.getAllDestinations(parameters.type)`, without restriction to `getMostRecentRuntime`.
With parameter it collects simulator only from latest runtime (10.2).

**Comment by renep** [comment]
Please test the latest develop version.

**Comment by Doxxer** [comment]
It works with xcode-plugin version `0.14.5.develop.80`
