### ISSUE TITLE
Gradle warning: Cannot assign 'String' to 'Class<Configuration>'

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#327]
I'm using version `0.14.4` of the Gradle Xcode plugin with version `3.2.1` of Gradle and I'm getting a warning for the `configuration` assignment as follows:

    Cannot assign 'String' to 'Class<Configuration>'

Should I be worried? Am I doing something wrong? This is what my `bulid.gradle` file looks like (with all the unrelated bits stripped off):

    plugins {
        id 'org.openbakery.xcode-plugin' version '0.14.4'
    }

    xcodebuild {
        configuration = 'Debug'
    }

**Comment by renep** [comment]
I cannot reproduce your issue.

I have run a test using the Swift Example project: https://github.com/openbakery/gradle-xcodePlugin/tree/master/example/iOS/SwiftExample

This is the output:
```
bash-3.2$ xcodebuild -version
Xcode 8.2
Build version 8C38
bash-3.2$ ./gradlew -version

------------------------------------------------------------
Gradle 3.2.1
------------------------------------------------------------

Build time:   2016-11-22 15:19:54 UTC
Revision:     83b485b914fd4f335ad0e66af9d14aad458d2cc5

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Mac OS X 10.11.6 x86_64

bash-3.2$ cat build.gradle
plugins {
	id 'org.openbakery.xcode-plugin' version '0.14.4'
}

apply plugin: 'org.openbakery.xcode-plugin'


xcodebuild {
	configuration = 'Debug'
	scheme = 'SwiftExample'
	target = 'SwiftExample'

	destination {
		platform = 'iOS Simulator'
		name = 'iPhone 6'
		os = '10.2'
	}
}

bash-3.2$ ./gradlew clean  test
:deploygateClean
:hockeyappClean
:keychainClean
:provisioningClean
:xcodebuildClean
:clean
:cocoapodsInstall
:simulatorKill
:xcodebuildConfig
:xcodetest

Run tests for: iPhone 6/iOS Simulator/10.2
2 tests completed
All 2 tests were successful
:test

BUILD SUCCESSFUL
```

**Comment by adil-hussain-84** [comment]
Hey @renep, sorry, I forgot to say: The build does actually work fine. The warning I get is in my IDE (IntelliJ IDEA Ultimate 2016.3) telling me that a `String` cannot be assigned to `Class<Configuration>`. Just looked into it a bit more and looks like your plugin is okay. For some reason my IDE is resolving the `configuration` attribute in my `build.gradle` file to be an object of type `org.gradle.api.artifacts.Configuration` rather than a simple `String`.
