### ISSUE TITLE
Incremental unit test launching

### ISSUE THREAD

**Issue by la-urre** [openbakery/gradle-xcodePlugin#328]
I want my unit tests to be launched only if really needed. If I launch the xcodetest task twice, I want the test launching step to be skipped, and the task marked UP-TO-DATE.

I don't know if implementing this feature is possible, as it would need to read the xcodeproj and check each referenced file to see if they have changed, sounds a bit complicated.

Anyway, it can be done directly in the gradle script, I put the code for reference, but I think this could appear in a documentation page, to help future users setup this.

```
xcodetest.inputs.dir "MyProjectFolder"
xcodetest.outputs.file "$buildDir/test/test-results.xml"
```

**Comment by renep** [comment]
What is the reason you call `xcodetest` twice?

**Comment by laurre** [comment]
My Xcode project is part of a more complete solution, which contains other tools. During development on these other tools, I regularly call my gradle script to check everything is ok. In this situation, I don't want the tests to be launched again if nothing related to the unit tests and to my Xcode project has changed. That is just gradle incremental build stuff.

**Comment by renep** [comment]
Pfff, gradle or the plugin itself does not know much about the what xcodebuild compiles or if something related has changed.
So this is not easy to change. Therefor I will not address this issue, because there is lots of other stuff that I find more important.
