### ISSUE TITLE
Strange keychainCreate error

### ISSUE THREAD

**Issue by huangjimmy** [openbakery/gradle-xcodePlugin#330]
My configuration is as follows

macOS 10.12.1 (16B2555)
Xcode Version 8.2 (8C38)
org.openbakery:xcode-plugin:0.14.+

------------------------------------------------------------
Gradle 3.1
------------------------------------------------------------

Build time:   2016-09-19 10:53:53 UTC
Revision:     13f38ba699afd86d7cdc4ed8fd7dd3960c0b1f97

Groovy:       2.4.7
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_05 (Oracle Corporation 25.5-b02)
OS:           Mac OS X 10.12.1 x86_64

When I build my iOS project, I keep seeing the following error messages

:xcodebuild
Done
:keychainCreate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':keychainCreate'.
> Command failed to run (exit code 1): 'security set-key-partition-list -S apple: -k -D -t private'
  Tail of output:
      0x00000007 <blob>=<NULL>
      0x00000008 <blob>=0x7B38373139316361322D306663392D313164342D383439612D3030303530326235323132327D00  "{87191ca2-0fc9-11d4-849a-000502b52122}\000"
      0x00000009 <uint32>=0x00000049  "\000\000\000I"
      0x0000000A <uint32>=0x00000100
      0x0000000B <uint32>=0x00000100
      0x0000000C <blob>=0x0000000000000000
      0x0000000D <blob>=0x0000000000000000
      0x0000000E <uint32>=0x00000000
      0x0000000F <uint32>=0x00000000
      0x00000010 <uint32>=0x00000001
      0x00000011 <uint32>=0x00000000
      0x00000012 <uint32>=0x00000000
      0x00000013 <uint32>=0x00000001
      0x00000014 <uint32>=0x00000001
      0x00000015 <uint32>=0x00000001
      0x00000016 <uint32>=0x00000000
      0x00000017 <uint32>=0x00000000
      0x00000018 <uint32>=0x00000000
      0x00000019 <uint32>=0x00000000
      0x0000001A <uint32>=0x00000001

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 34.376 secs

If I run "security set-key-partition-list -S apple: -k -D -t private" in terminal, I encounter "security: SecKeychainItemSetAccessWithPassword: The user name or passphrase you entered is not correct."

I have no clue how to fix this problem.

I also search source code of gradle-xcodePlugin and I cannot find anything similar to "set-key-partition-list".

**Comment by renep** [comment]
Use the 0.14.4 version, not the develop for now. I know this issue.

**Comment by huangjimmy** [comment]
Thanks, I use 0.14.4 and problem solved.

It seems that the set-key-partition-list command is added to solve 316.

**Comment by renep** [comment]
Was introduces with #316, so I have marked it als duplication, because when #316 is fixed, also this is fixed.

**Comment by huangjimmy** [comment]
I successfully built a new IPA with latest develop 83 build.
