### ISSUE TITLE
Include SwiftLint support

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#333]
https://github.com/realm/SwiftLint

**Comment by icecrystal23** [comment]
SwiftLint can be included directly into your project and build phases.  What specifically would you like this plugin to do with it?

**Comment by renep** [comment]
The idea is that nothing has to be configured at the project itself. So if you have a vanilla swift project, just execute e.g. `gradle lint` you get a report.

**Comment by icecrystal23** [comment]
Would you still get the inline messages and build breakages when running in the Xcode GUI with that, though?
