### ISSUE TITLE
Useless comments in JavaDoc

### ISSUE THREAD

**Issue by aaabramov** [openbakery/gradle-xcodePlugin#338]
Some files like [AbstractKeychainTask.groovy](https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/signing/AbstractKeychainTask.groovy) have useless auto generated javadoc comments. Should they be removed?

```
/**
 * Created with IntelliJ IDEA.
 * User: rene
 * Date: 23.08.13
 * Time: 11:39
 * To change this template use File | Settings | File Templates.
 */
```

**Comment by renep** [comment]
Sure 👍

**Comment by Abrasha** [comment]
@renep, in few days I will create corresponding pull request

**Comment by Abrasha** [comment]
@renep, just to ensure.
The whole comment should be removed?

**Comment by renep** [comment]
yes

**Comment by Abrasha** [comment]
@renep, and what about comments like this?

```
/**
 * Created by rene on 08.11.16.
 */
```

**Comment by renep** [comment]
I don't know what the best way is for these class comments. On the one hand it could be nice to know the author of a file and when it was created, but this information also is stored in git.

So this is not very important to me, what the header comment of a class is, so feel free to make a suggestion what you think is appropriate ;-)

**Comment by janosvitok** [comment]
It seems that this issue can be closed.

**Comment by aaabramov** [comment]
> It seems that this issue can be closed.

Agree. Thanks for pointing out 👍
