### ISSUE TITLE
Specify working directory for project

### ISSUE THREAD

**Issue by aaabramov** [openbakery/gradle-xcodePlugin#339]
How can I specify the working directory for building iOS project?

For example my `build.gralde` script is in another directory than iOS project:

    xcodebuild {
        projectFile = '../../../Example.xcodeproj'
    }

This configuration doesn't work and says that there is no such Xcode project in this directory.
By this I mean the directory where `build.gradle` file is located.

**Comment by renep** [comment]
The implementation for this is not complete yet. The parameter is only used when parsing projects settings, but not for the build itself.

The two main reasons why this is the case is
1. in my projects a always have the build.gradle in the same directory as the xcode project, so I don't need this.
2. If I don't need something then the priority is most of the time low to implement it.

**Comment by Abrasha** [comment]
@renep, thank you

Is there any workaround for this?

**Comment by renep** [comment]
hmm, I not sure if you can set the gradle projectDir, because xcodebuild in configured using the projectDir:

see https://github.com/openbakery/gradle-xcodePlugin/blob/master/plugin/src/main/groovy/org/openbakery/XcodeBuildTask.groovy#L51

**Comment by Abrasha** [comment]
I am currently looking through sources to find the solution.

Nevertheless, thank you for replying :)
