### ISSUE TITLE
Single command to create ipa?

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#351]
I find I have to run the `gradle archive` command followed by the `gradle package` command in order to build an ipa file (or `gradle archive package`). If I run the `gradle package` command by itself I get an `Archive does not exist` error. Is this correct behaviour or should the `gradle package` command work by itself?

**Comment by renep** [comment]
That is intentional, because you can have an xcarchive already from an previous build that you want to code sign with the package task.
So you have to run `gradle archive package`, but you can also define a custom task in your build file.
