### ISSUE TITLE
gradle-xcodePlugin created ipa is not installable

### ISSUE THREAD

**Issue by YogeshBharate** [openbakery/gradle-xcodePlugin#354]
I have created the .ipa using following gradle script.

xcodebuild {
	scheme = 'Test'
	configuration='Release'
	target = 'Test'
	ipaFileName = "Test"
	workspace = 'Test.xcworkspace'
	simulator = false
	signing {
		identity = 'iPhone Developer'
		certificateURI = new File('/Volumes/DATA/CI/gradle/Test-enterprise.p12').toURI()
		certificatePassword = 'password'
	    mobileProvisionURI = new File('/Volumes/DATA/CI/gradle/Test.mobileprovision').toURI()
	}
	additionalParameters = "EMBEDDED_CONTENT_CONTAINS_SWIFT=NO"
	destination = ['iPad Air', 'iPad Air 2', 'iPad Pro', 'iPad Retina']
}

but the .ipa is not installable on device. Its shows installing that ipa on iTune but after sometime it does not install. Is there anything missing in above xcodebuild task ??? If any please suggest.

**Comment by renep** [comment]
try this config:
```
xcodebuild {
	scheme = 'Test'
	configuration='Release'
	target = 'Test'
	simulator = false
	signing {
		certificateURI = new File('/Volumes/DATA/CI/gradle/Test-enterprise.p12').toURI()
		certificatePassword = 'password'
		mobileProvisionURI = new File('/Volumes/DATA/CI/gradle/Test.mobileprovision').toURI()
	}
	additionalParameters = "EMBEDDED_CONTENT_CONTAINS_SWIFT=NO"
}
```

You do not need the `identity` parameter because this is fetch from the entry in the keychain that was created with the p12.
-> this could be your problem, because the identity must be correct, so if you do not specify anything the proper one is used.

For a device build you also do not need the `destination` parameter, but if you have set the parameters, than it doesn't matter because it is ignored.

**Comment by YogeshBharate** [comment]
@renep Thank you for your reply.
Its works for me and its creates the installable .ipa file. but the problem is that, the size of app increase to double. Normal .ipa created using xcode its size is 70 MB after installation but when i install the gradle created ipa size its increases to 140MB. How should I reduce this size ? and why the app size increase to double. ?
