### ISSUE TITLE
Wrong information in the *xcodebuild.scheme* parameter documentation

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#355]
The documentation [here](https://openbakery.org/gxp/parameters/xcodebuild.html) says that if the `scheme` parameter is specified then the `configuration` parameter is ignored. This is incorrect in the case of a Cocoa Touch Framework project. The only way I can see to distinguish between building a `Debug` vs `Release` variant of the Framework is by specifying the `configuration` parameter.

**Comment by renep** [comment]
The Documentation is wrong here. See https://github.com/openbakery/gradle-xcodePlugin/blob/master/libxcode/src/main/groovy/org/openbakery/xcode/Xcodebuild.groovy#L131
