### ISSUE TITLE
Task Ordering

### ISSUE THREAD

**Issue by AyalCiobotaru** [openbakery/gradle-xcodePlugin#365]
I've been using the plugin for a little while now and I'm super thankful for the work you've put in. 

I was trying to do some basic task ordering at the end of my script to make sure the tasks run in the order I want however after applying these lines of code:

```
// Task ordering
xcodebuild.dependsOn bumpVersion
package.mustRunAfter 'archive'
deployToShare.mustRunAfter 'package'
```

I get the error 
```
Could not find method dependsOn() for arguments [task ':bumpVersion'] on object of type org.openbakery.XcodeBuildPluginExtension.
```

I thought since you extend the defaultTask that task ordering such as mustRunAfter() and dependsOn() is automatically implemented.

-Ayal

**Comment by renep** [comment]
I have a task defined like this:

```
task testCore(type:org.openbakery.XcodeTestTask) {
	scheme = 'Core'
	target = 'Core'
}

/*
testCommon and testApp look similar to testCore, only scheme and Target are different
*/

task runAndTest(type:org.openbakery.coverage.CoverageTask) {
	dependsOn.add('testCore')
	dependsOn.add('testCommon')
	dependsOn.add('testApp')
	
	testCore.mustRunAfter tasks.xcodetest
	testCommon.mustRunAfter tasks.xcodetest
	testApp.mustRunAfter tasks.xcodetest
}
```

**Comment by AyalCiobotaru** [comment]
I'm using the default task xcodebuild so I didn't define it with the 'task' parameter in front of it. I also didn't put the package or archive tasks into my code but I'm using the default ones provided with the plugin in order to generate the ipa.

I was hoping to be able to just order everything outside of all the task functions at the bottom of the script. Is that not possible?

**Comment by renep** [comment]
this should work: 

```
task bumpVersion {
  doLast {
    println "bumpVersion"
  }
}

tasks.xcodebuild.dependsOn tasks.bumpVersion
tasks.package.dependsOn tasks.archive
```

**Comment by AyalCiobotaru** [comment]
Awesome! That worked. Thank You!

I've been able to do task ordering before without having to put 'tasks.' in front the task name. Any idea why its necessary here?

**Comment by phatblat** [comment]
@AyalCiobotaru without the `tasks.` prefix, `xcodebuild` is getting resolved to the `XcodeBuildPluginExtension` class because that's what handles the `xcodebuild {...}` configuration.
