### ISSUE TITLE
 java.io.IOException: Cannot run program "plutil" (in directory "."): error=2, No such file or directory

### ISSUE THREAD

**Issue by mshah-nisum-com** [openbakery/gradle-xcodePlugin#366]
My build.gradle file
plugins {
  id "org.openbakery.xcode-plugin" version "0.14.3"
}

xcodebuild {
  target = '<Project_Folder>'
}

task wrapper(type: Wrapper){
        gradleVersion = '2.5'
}

when i am running "gradle xcodebuild"

I am getting this error,
![image](https://user-images.githubusercontent.com/30224597/30288432-87fa9256-96dd-11e7-860e-1d2389b6c36a.png)

In the project folder, i have two .plist files.

I am using Centos 7 OS, and i have tried it with Windows 7 Os also. The same error persists.

Can you please help me out on fixing this issue.

**Comment by renep** [comment]
The plugins runs only on macOS.

**Comment by mshah-nisum-com** [comment]
Ok. Will try to get Mac OS. May be in future we can get the xcode bundle and based on Operating Systems, so that we can run plugin as platform independent..

**Comment by saravnandm** [comment]
Hi,
I'm also facing the same error when running in the Jenkins job. Any fixes?

> Task :xcodebuildConfig FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xcodebuildConfig'.
> java.io.IOException: Cannot run program "plutil" (in directory "."): error=2, No such file or directory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by renep** [comment]
What is you operating system and version?
