### ISSUE TITLE
Not able to create .ipa file, Even after providing the sigining information in gradle script

### ISSUE THREAD

**Issue by mshah-nisum-com** [openbakery/gradle-xcodePlugin#367]
plugins {
 id "org.openbakery.xcode-plugin" version "0.15.0"
}

xcodebuild {
 target = 'random'
 scheme = 'random'
 workspace = 'random.xcworkspace'
 type = 'iOS'
 projectFile = 'random.xcodeproj'
 configuration = 'Debug'
 simulator = 'true'
 signing {
       certificateURI = 'file:///Users/some/Certificates/some.p12'
       certificatePassword = 'some'
       mobileProvisionURI = [
               'file:///Users/some/Certificates/random-3.mobileprovision'
               ]
       }
}

Above is my gradle script file and now i am trying to create an .ipa file and not able to create.
I am using "gradle xcodebuild archive package" still it create .app in sym/Debug-iphoneos folder
Can you please help on the steps to generate an .ipa file asap. Please.

**Comment by mshah-nisum-com** [comment]
I am getting this as output 
![image](https://user-images.githubusercontent.com/30224597/30613395-c00ec404-9d3c-11e7-94cc-ebba3243a21e.png)

**Comment by resisi** [comment]
>  not a device build, so no codesign and packaging needed

means you build the project for simulator and not for the app store or a real device

> simulator = 'true'

change to false and everything should works fine

**Comment by mshah-nisum-com** [comment]
Thank you @resisi , I had figured that out long time back. I was able to create ipa by setting simulator='false'.
Forgot to close this issue.
