### ISSUE TITLE
Does it work with latest gradle and swift

### ISSUE THREAD

**Issue by nagkumar** [openbakery/gradle-xcodePlugin#374]
is this pugin compatible with gradle 4.x
and Swift 4 & xcode 9

any have tried..pl. share your feedback

**Comment by renep** [comment]
Yes, the latest version 0.15.1 works with Swift 4 and Xcode 9.
I have created this plugin to build the iOS projects I'm working on. This are mixed Projects that uses Obj-C and Swift, but also pure Swift projects.
I also use the projects for my continuous delivery pipeline that codesigns and distributes the Apps (to iTunesConnect)

**Comment by strawlink** [comment]
@renep Is the 0.15.1 release stable? The README.md says the latest is 0.15.0.

**Comment by renep** [comment]
Yes. I have fixed the README.md
