### ISSUE TITLE
The repository.openbakery.org maven repo is down

### ISSUE THREAD

**Issue by adil-hussain-84** [openbakery/gradle-xcodePlugin#376]
I'm seeing that the [repository.openbakery.org](http://repository.openbakery.org) site is down and thus the maven repo that's hosting the `org.openbakery.xcode-plugin` plugin is unreachable.

Are there plans to publish the `org.openbakery.xcode-plugin` plugin to jcenter or mavenCentral to get around the problem of being unable to pull the plugin down when [repository.openbakery.org](http://repository.openbakery.org) is down?

**Comment by renep** [comment]
I can reach repository.openbakery.org e.g.:
http://repository.openbakery.org/org/openbakery/xcode-plugin/maven-metadata.xml

Also you find the version 0.15.1 at plugins.gradle.org: https://plugins.gradle.org/plugin/org.openbakery.xcode-plugin
