### ISSUE TITLE
java.io.IOException: Cannot run program "/Contents/Developer/usr/bin/simctl" (in directory "."): error=2, No such file or directory

### ISSUE THREAD

**Issue by varris** [openbakery/gradle-xcodePlugin#397]
I have build.gradle

buildscript {
	repositories {
		maven { url('http://repository.openbakery.org') }
		mavenCentral()
    }

	dependencies {
	    classpath "org.openbakery:xcode-plugin:0.15.+"
	}
}

apply plugin: 'org.openbakery.xcode-plugin'

xcodebuild {
    target = 'dev-ios'
	scheme = 'dev-ios'
	// configuration = 'Test'
	destination = ['iPhone 8' ]
}

after ./gradlew -p dev-ios/ build
have error 
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dev-ios:xcodebuild'.
> java.io.IOException: Cannot run program "/Contents/Developer/usr/bin/simctl" (in directory "."): error=2, No such file or directory

I have xcode 10, gradle 4.7

**Comment by renep** [comment]
The command for simctl should be:
`/Application/Xcode.app/Contents/Developer/usr/bin/simctl`

The Xcode path is determined using the following command:
`xcode-select -p`
Could you please run the command and see what your output is. This should be:
`/Applications/Xcode.app/Contents/Developer`

You can also do this with the build.gradle by adding:
```
task checkSimctl {
  doLast {
    def commandRunner = new org.openbakery.CommandRunner()
    println new org.openbakery.xcode.Xcode(commandRunner).getSimctl()
  }
}
```
and then execute:
`./gradlew checkSimctl`

**Comment by varris** [comment]
Hello,

I did that and  got
varis:~/Projects/sw_where_common [master]$ ./gradlew -p dev-ios/ checkSimctl

> Configure project :platform-ios
feature GRADLE_METADATA is not enabled: publication is disabled

> Task :dev-ios:checkSimctl
/Contents/Developer/usr/bin/simctl

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed

**Comment by varris** [comment]
closing because after  updating to xcode 10 need update command line tools to xcode 10

**Comment by varris** [comment]
don't forget update command line tools

**Comment by varris** [comment]
I was wrong still have the problem

**Comment by varris** [comment]
the problem is gradle 4.7
when I have changed your repo to 4.7

got the same error with example build

./gradlew -p example/tvOS/Example_tvOS_Swift/ build
> Task :xcodebuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xcodebuild'.
> java.io.IOException: Cannot run program "/Contents/Developer/usr/bin/simctl" (in directory "."): error=2, No such file or directory

**Comment by renep** [comment]
can you run `xcode-select -p`

**Comment by varris** [comment]
xcode-select -p
/Applications/Xcode.app/Contents/Developer

**Comment by varris** [comment]
the problem is gradle.
if have gradle >= 4.7 it will run gradle daemon for speeding up the build.
sometimes that daemon caches wrong path value.

the workaround is run gradle with no daemon option
./gradlew --no-daemon -p dev-ios/ test
