### ISSUE TITLE
Can't successfully upload to TestFlight after upgrading to XCode 10.1

### ISSUE THREAD

**Issue by wizofaus** [openbakery/gradle-xcodePlugin#407]
Currently I'm using open-bakery to build and sign the ipa for uploading to TestFlight, which I do separately using altool.  It had been working fine with Xcode 9.2 but then we started getting warnings about needing to build with Xcode 10.1 before March, so I made the necessary changes to support that.
Now it still uploads fine but then after an unbelievably long wait I get an email from Apple saying 

Invalid Swift Support - The files libswiftCoreGraphics.dylib, libswiftCoreMedia.dylib, libswiftDarwin.dylib, libswiftCoreAudio.dylib, libswiftos.dylib, libswiftQuartzCore.dylib, libswiftCoreData.dylib, libswiftContacts.dylib, libswiftFoundation.dylib, libswiftMetal.dylib, libswiftCoreFoundation.dylib, libswiftAVFoundation.dylib, libswiftCoreImage.dylib, libswiftObjectiveC.dylib, libswiftsimd.dylib, libswiftUIKit.dylib, libswiftDispatch.dylib, libswiftCore.dylib don’t match /Payload/PaymentApp.app/Frameworks/libswiftCoreGraphics.dylib, ...

And the app is removed from TestFlight.

I've tried playing around with the "bitcode" and "useXcodebuildArchive" options but to no avail.

When I archive and upload to TestFlight from within Xcode itself it works fine.

I have confirmed in the ipa created by open-bakery that, as suggested, the dylib files in the "SwiftSupport" folder are a (slightly) different size to the ones in the "Payload/xxx.app/Frameworks" folder.

BUT the same is true for the ipa created by XCode (that uploaded successfully) - the difference is that the dylib files under Payload/xxxx.app/Frameworks are actually considerably smaller (about half the size).
This is despite the fact I unselected the option to strip symbols etc.

I'm a bit stuck at this point, has anybody done any work ensuring that XCode 10.1 packages can be successfully uploaded to TestFlight?

**Comment by wizofaus** [comment]
PS.. where is the documentation about how to control the behaviour of the archiving/packaging, specifically wrt app thinning, stripping symbols, building symbol maps etc.?

**Comment by phatblat** [comment]
@wizofaus Use a separate scheme for release
