### ISSUE TITLE
Xcode 10.2 - An empty identity is not valid when signing a binary for the product type 'Application'

### ISSUE THREAD

**Issue by milfar** [openbakery/gradle-xcodePlugin#411]
Hi, I am getting the below error when I try to build my project.  Any help would be much appreciated. Thanks

I am using - 

org.openbakery:xcode-plugin:0.15.4.develop.+
gradle 5.3.1
Xcode 10.2

-----

  Build settings from command line:
      CODE_SIGN_IDENTITY = 
      CODE_SIGNING_REQUIRED = NO
      DSTROOT = /Users/milfar/build/client/build/dst
      OBJROOT = /Users/milfar/build/client/build/obj
      SHARED_PRECOMPS_DIR = /Users/milfar/build/client/build/shared
      SYMROOT = /Users/milfar/build/client/build/sym
  
  note: Using new build system
  note: Planning build
  note: Constructing build description
  Build system information
  error: An empty identity is not valid when signing a binary for the product type 'Application'. (in target 'RRiOSClient')
  
  ** BUILD FAILED **

**Comment by renep** [comment]
I can only guess, because you did not tell what build target you are running, what your build.gradle looks like, do you build for the device or simulator?

**Comment by gz2jbt** [comment]
adding:
additionalParameters = "CODE_SIGNING_ALLOWED=NO"
to: xcodebuild step
in: build.gradle
worked for me

**Comment by milfar** [comment]
> I had the same error. Adding:
> additionalParameters = "CODE_SIGNING_ALLOWED=NO"
> to xcodebuild step in build.gradle worked for me

that worked! thanks!

**Comment by renep** [comment]
There is already a new develop version that contains this fix: https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version
