### ISSUE TITLE
altool location has changed in Xcode 11

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#414]
To: `/Applications/Xcode.app/Contents/Developer/usr/bin/altool`

**Comment by RomanPodymov** [comment]
Hello @renep 
Is it fixed in some branch?

**Comment by renep** [comment]
Yes you can use the `develop` Version. See: https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

With every commit there is always a develop version build, so if you see a commit in an issue log, then it should be included in the develop version.

I will try to release a new major version soon, because in the next version there must be more changes to be full compatible with gradle 6.+.
