### ISSUE TITLE
IPA is rejected by AppstoreConnect

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#416]
> ITMS-90426: Invalid Swift Support - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

When building the IPA with Xcode 11 the `SwiftSupport/iphoneos` folder is missing with the swift support library.

**Comment by renep** [comment]
In the create `xcarchive` the SwiftSupport folder is missing.

**Comment by renep** [comment]
This is fixed with https://github.com/openbakery/gradle-xcodePlugin/commit/e9533284981b179d98b8f2682a6eb5d4f23e833e

You can use the latest develop version that contains the fix: https://github.com/openbakery/gradle-xcodePlugin/tree/develop#current-develop-version

**Comment by jorgepf** [comment]
Thank you renep :)

Now the container "*.xcarchive" includes the Swiftsupport folder but when the plugin is trying to build the package the execution fails.

`14:48:19.950 [DEBUG] [org.openbakery.CommandRunner] Run command: '/usr/libexec/PlistBuddy __MYWORKSPACE__/build/dev/build/package/Payload/__MYAPP__.app/Info.plist -c Print :CFBundleExecutable'
14:48:19.950 [DEBUG] [org.openbakery.CommandRunner] with working directory: . (__MYWORKSPACE__/.)
14:48:19.960 [DEBUG] [org.openbakery.CommandRunner] Run command: 'xcodebuild clean -showBuildSettings'
14:48:19.960 [DEBUG] [org.openbakery.CommandRunner] with working directory: __MYWORKSPACE__/build/dev (__MYWORKSPACE__/build/dev)
14:48:20.822 [DEBUG] [org.openbakery.CommandRunner] Exit Code: 66
....
14:48:20.882 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Command failed to run (exit code 66): 'xcodebuild clean -showBuildSettings'
14:48:20.882 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Tail of output:
14:48:20.882 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   xcodebuild: error: The directory __MYWORKSPACE__/build/dev does not contain an Xcode project, workspace or package.
`

I don't know why is changing my working directory.

This is the stack:

`14:48:20.887 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.CommandRunner.run(CommandRunner.groovy:98)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.CommandRunner$run$2.callCurrent(Unknown Source)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.CommandRunner.runWithResult(CommandRunner.groovy:203)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.CommandRunner$runWithResult$1.callCurrent(Unknown Source)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.CommandRunner.runWithResult(CommandRunner.groovy:192)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.CommandRunner$runWithResult$0.call(Unknown Source)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.xcode.Xcodebuild.loadBuildSettings(Xcodebuild.groovy:329)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.xcode.Xcodebuild.getBuildSetting(Xcodebuild.groovy:335)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.xcode.Xcodebuild.getToolchainDirectory(Xcodebuild.groovy:302)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.tools.Lipo.getLipoCommand(Lipo.kt:59)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.tools.Lipo.getArchs(Lipo.kt:20)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.assemble.AppPackage.updateArchsForSwiftLibs(AppPackage.kt:127)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.assemble.AppPackage.addSwiftSupport(AppPackage.kt:120)
14:48:20.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.assemble.AppPackage$addSwiftSupport.call(Unknown Source)
14:48:20.889 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.openbakery.packaging.PackageTask.packageApplication(PackageTask.groovy:121)
14:48:20.889 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
`

Surely the problem it's in my config but:

When I execute in my terminal ''xcodebuild clean -showBuildSettings -workspace __MYWORKSPACE__/__MYAPP__.xcworkspace -scheme dev" from "__MYWORKSPACE__/build/dev" seems to work.

https://github.com/openbakery/gradle-xcodePlugin/blob/develop/plugin/src/main/groovy/org/openbakery/packaging/PackageTask.groovy#L117 -> These empty params could be the problem? (I don't know the library deeply. I'm just trying to help)

Thank you :)
