### ISSUE TITLE
Archive task fails

### ISSUE THREAD

**Issue by aditisaini91** [openbakery/gradle-xcodePlugin#429]
Hi,

I was facing the issue : https://github.com/openbakery/gradle-xcodePlugin/issues/416. But the build process would work completelty fine, just the swift support folder missing.
When I changed  the plugin version from  "org.openbakery:xcode-plugin:0.19.+" to  "org.openbakery:xcode-plugin:0.20.0.develop.+", I got a following build error :

A problem was found with the configuration of task ':archive'.
> Cannot write to file '...../archive' specified for property 'outputDirectory' as it is a directory.

I am using gradle version 4.1.

Please let me know how this could be fixed.

Thanks in advance

**Comment by renep** [comment]
Can you upgrade to gradle version 5 or newer. The latests changes in the plugin was to be compatible with gradle 6.+.

**Comment by aditisaini91** [comment]
That worked! thank you so much!

**Comment by GCMSGulfstream** [comment]
I am using Gradle 6.5 and am getting this error.  I've every 5.x and 6.x Gradle release with the same result.
