### ISSUE TITLE
Is there any way to build multiple targets at once? 

### ISSUE THREAD

**Issue by vasanth23** [openbakery/gradle-xcodePlugin#44]
#### I am using the following script which works fine with single target but what I am looking for is multiple targets

My Current Script

```
buildscript 
{
    repositories 
    {
        maven 
        {
            url('http://openbakery.org/repository/')
        }
        mavenCentral()
    }
    dependencies 
    {
        classpath group: 'org.openbakery', name: 'xcodePlugin', version: '0.9.2'
    }
}
apply plugin: 'xcode'

xcodebuild 
{   
    scheme = 'TestBuildGradle'
    configuration = 'Debug'
    sdk =  'iphonesimulator7.0'
    target = 'TestBuildGradle'
    unitTestTarget = 'TestBuildGradleTests'
    destination 
    {
        platform = 'iOS Simulator'
        name = 'iPhone Retina (3.5-inch)'
        os='7.0'
    }
}
```
#### I am looking for something like

```
target = 'alltargets'
```

or

```
target = ['Target1', 'Target2', 'Target3', .....]
```

**Comment by AkhileshwarBV** [comment]
Hi renep
Thank you for the replay

I am getting an error says

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build'.
> No 'scheme' or 'target' specified, so do not know what to build

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 3.707 secs
pbxddxl:Test deltatechnology$ 


Here I am seining my build script
---------------------------------------------
buildscript {
repositories {
maven {
url('http://openbakery.org/repository/')
}
mavenCentral()
}
dependencies {
classpath group: 'org.openbakery', name: 'xcodePlugin', version: '0.9.+'
}
}
apply plugin: 'xcode'

xcodebuild {
configuration='Release'
sdk = 'iphoneos'
//target = 'Test'
additionalParameters = ["Test"]
signing {
identity = 'iPhone Distribution: Republic Services Inc. (YKXBJ5R297)'
certificateURI = 'file://localhost/Users/deltatechnology/Desktop/Cer/EmployeeDirectory/PrivateKey.p12'
certificatePassword = 'Password'
mobileProvisionURI = 'file://localhost/Users/deltatechnology/Desktop/Cer/EmployeeDirectory/Employee_Directory_Adhoc-3.mobileprovision'
}


}

**Comment by judgeaxl** [comment]
A variation of this is when one needs to build multiple targets with different settings, for instance I have a project, which I cannot easily modify, which has an iOS target, and an OS X target, and I need to build both, but with different settings, most specifically the sdk property differs. Is it possible to inherit and modify the xcodebuild properties within another task? Say, like I would with Copy, or Exec?

**Comment by renep** [comment]
Not now. I have this in mind for a future version, because this makes also sense for the code signing settings. I'm now in a brainstorming phase were I collect what can be done better, and what I want of the plugin. 
Next up there will only be some minor changes in the next release and afterwards I want start with with bigger changes ;-)

**Comment by judgeaxl** [comment]
OK, thanks. Right now I don't actually need any signing, or other features, just two vanilla xcodebuild runs after each other, so I think I'll solve it with two Exec tasks for now. The whole multiple targets/settings/runs concept seems a bit alien to Gradle in general.

**Comment by jonnermut** [comment]
Being able to run multiple runs of xcodebuild with different settings in the one gradle run would be very useful. Eg test on simulator, then build a release build.
Or test on iOS, test on OSX.
I think some other plugins do this by generating dynamic tasks.

**Comment by renep** [comment]
I know that this would be very useful, and this is one of the next things that I will address.

**Comment by rcbop** [comment]
Any progress on this? :)

**Comment by renep** [comment]
Not much...

**Comment by renep** [comment]
With 0.14.2 you can define tasks for the xcodebuild so that you can run multiple targets in one build process.
Next step is to support gradle multi project builds
