### ISSUE TITLE
Coverage broken in 0.20.1 release

### ISSUE THREAD

**Issue by kried** [openbakery/gradle-xcodePlugin#448]
In release 0.20.1 in pull request [Added that skipped tests are supported](https://github.com/openbakery/gradle-xcodePlugin/commit/1e3c23d010e6f179eb68a9b11346938858633954#diff-36a308266b33c7e8da4c6381da3b0c8ee89a4e28326e1d9176750a1232435f6b) coverage.setTestResultDestinations() method call was removed from XcodeTestTask. It was previously added in [Updated coverage for new xcode 9 report path](https://github.com/openbakery/gradle-xcodePlugin/commit/7207c48998b3902ed3701c8cb921c602ab8ce568)

With last release coverage fails with error `build/derivedData/Build/Intermediates/CodeCoverage/Coverage.profdata' specified for property 'profileData' does not exist.`

**Comment by otis78** [comment]
Is there any news about this issue?

**Comment by renep** [comment]
Nope! 
Normally I'm quite busy and coverage is only a low priority for my. I do TDD so I write a lots of tests, but the coverage metric is not important to me. So it is not very likely that this will change anytime soon.

Don't get me wrong. I use the gradle-xcodePlugin to build all my projects, but the my priority is at building, running unit tests and distribution (+ codesign)

But pull requests are always welcome 😉.
