### ISSUE TITLE
OCLint support

### ISSUE THREAD

**Issue by DaleJefferson** [openbakery/gradle-xcodePlugin#57]
It would be great to support json compile database file output so we could add a OClint task.

**Comment by renep** [comment]
Implemented in the development branch.

There are 2 new tasks 'oclint' and and 'oclintReport'
oclint is 'clean xcodebuild oclintReport'

oclintReport installs oclint and create a report that is found in 'build/oclint'.

Configuration looks like this:

```
oclint {
	maxPriority2 = 100			
	maxPriority3 = 999			
	excludes = [ 'Pods' ]
	rules = [
				"LONG_LINE=200",
				"LONG_VARIABLE_NAME=64",
				"LONG_METHOD=150",
				]
}
```

For more details see the parameters documentation.

(I will create a 0.11.4 release hopefully later this week)
