### ISSUE TITLE
support for xctool

### ISSUE THREAD

**Issue by jrikhof** [openbakery/gradle-xcodePlugin#66]
I would like to switch to xctool instead of xcodebuild. Think this could be easily supported to add a boolean useXCTools or something

**Comment by Nathan-Smith** [comment]
+1 on xctool support, at least an option to invoke xctool instead of xcodebuild.

**Comment by jaredsburrows** [comment]
Even if xctool was added. You would still need to do `brew install xctool` first.

**Comment by renep** [comment]
I have no desire to support xctool so I close it
