### ISSUE TITLE
Doesn't work with Workspaces

### ISSUE THREAD

**Issue by kishyr** [openbakery/gradle-xcodePlugin#85]
It seems specifying "workspace = 'Name.xcworkspace'" in build.gradle does nothing and doesn't even look at the workspace file. Instead this is what happens when run:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'blockbreaker'.
> 0
```

**Comment by BamX** [comment]
Is there additional property like 'xcodeprojFile' in xcodebuild will be ever added?
